### ISSUE TITLE
使用elastice邮箱服务时 获取验证码时 500报错 已勾选允许http

### ISSUE THREAD

**Issue by TPC-Light** [AprilNEA/ChatGPT-Admin-Web#105]
<img width="1280" alt="Screen Shot 2023-06-21 at 21 44 15" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/62536247/62c21adc-9ba1-4e58-bb47-f56041712404">

**Comment by AprilNEA** [comment]
需要允许发件。
