### ISSUE TITLE
微信登录的反代怎么设置啊，大佬可以出个教程吗

### ISSUE THREAD

**Issue by xiebiao99** [AprilNEA/ChatGPT-Admin-Web#107]
微信登录的反代怎么设置啊，大佬可以出个教程吗
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/7df72f93-1191-4405-ab56-f6ce8f56ce5a)

**Comment by Cyvadra** [comment]
同问

**Comment by Cyvadra** [comment]
WECHAT_PROXY 留空即可

**Comment by AprilNEA** [comment]
如本地部署则只需添加公众平台对应服务器IP白名单即可，不再需要反代
