### ISSUE TITLE
邮箱注册的时候一直提示请输入手机验证码，邮箱注册不了

### ISSUE THREAD

**Issue by xiebiao99** [AprilNEA/ChatGPT-Admin-Web#108]
邮箱注册的时候一直提示请输入手机验证码，邮箱注册不了
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/a15d44f4-9cea-42db-b329-a5b526dc1b39)

**Comment by TPC-Light** [comment]
会不会是邮件服务环境变量设置错了，导致没有开启邮箱注册

**Comment by xiebiao99** [comment]
没有错，我用的mailgun邮件服务，第一次部署成功的时候都是可以注册邮件和登录正常使用的，但是现在最新版的就不行了

**Comment by TPC-Light** [comment]
> 没有错，我用的mailgun邮件服务，第一次部署成功的时候都是可以注册邮件和登录正常使用的，但是现在最新版的就不行了

![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/62536247/c74d449f-be26-44c0-8b8b-417d56e2c35b)
可以这里面看下报错代码

**Comment by xiebiao99** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/ddfb84f2-5604-4ff3-a8ac-6e7bc5e56f81)

zhe'g这个是需要在prisma数据库里面手动建表吗
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/e02fa2b7-0fe0-4894-beb7-1a2666a3ec01)

**Comment by xiebiao99** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/531fa68a-4af9-4fde-afa9-50cd923f3d15)

**Comment by TPC-Light** [comment]
> ![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/ddfb84f2-5604-4ff3-a8ac-6e7bc5e56f81)
> 
> 
> 
> zhe'g这个是需要在prisma数据库里面手动建表吗
> 
> ![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/e02fa2b7-0fe0-4894-beb7-1a2666a3ec01)
> 
> 

对 需要先本地push数据库结构到neon
具体可以看这个:https://caw.sku.moe/deploy/local#4-初始化数据库

**Comment by TPC-Light** [comment]
> ![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/531fa68a-4af9-4fde-afa9-50cd923f3d15)
> 
> 不用 本地部署才需要修改

**Comment by xiebiao99** [comment]
我本地push数据库的时候执行命令报错
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/9114fcac-b65b-4bdf-8709-e21c9b881719)

**Comment by TPC-Light** [comment]
> 我本地push数据库的时候执行命令报错
> 
> ![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/9114fcac-b65b-4bdf-8709-e21c9b881719)
> 
> apt install npm

npm install turbo --global

按顺序执行一下应该就行了

**Comment by xiebiao99** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/cf287e7d-d9da-4805-a099-83595506bfae)

**Comment by TPC-Light** [comment]
> ![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/cf287e7d-d9da-4805-a099-83595506bfae)
> 
> 

你是用的windows啊，我用的Linux整的，哈哈 不太会了

**Comment by TPC-Light** [comment]
> ![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/cf287e7d-d9da-4805-a099-83595506bfae)
> 
> 

有问题可以问问chatgpt

**Comment by xiebiao99** [comment]
好吧，那我直接在Neon的数据库里面执行sql文件后生成的表结构应该和本地push的一样吧
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/34bb0c7f-8cd2-451f-a50c-c429448bfe8c)

**Comment by xiebiao99** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/e575852f-7210-49f0-87cb-16d7593b9ba8)

**Comment by TPC-Light** [comment]
> 好吧，那我直接在Neon的数据库里面执行sql文件后生成的表结构应该和本地push的一样吧
> 
> ![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/34bb0c7f-8cd2-451f-a50c-c429448bfe8c)
> 
> 

一样的

**Comment by xiebiao99** [comment]
但是我这样生成表结构后在vercel部署成功后邮箱注册依然用不了，邮箱的环境变量配置也是对的，
这是我的地址：https://www.xbchat.top/#/auth
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/528b394f-d808-44c4-957a-897a783a7cb7)

**Comment by TPC-Light** [comment]
> 但是我这样生成表结构后在vercel部署成功后邮箱注册依然用不了，邮箱的环境变量配置也是对的，
> 
> 这是我的地址：https://www.xbchat.top/#/auth
> 
> ![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/528b394f-d808-44c4-957a-897a783a7cb7)
> 
> 
我这边注册提示incorrect password
我看了下浏览器日志是code获取错误
建议去vercel看看报错的日志

**Comment by TPC-Light** [comment]
> 但是我这样生成表结构后在vercel部署成功后邮箱注册依然用不了，邮箱的环境变量配置也是对的，
> 
> 这是我的地址：https://www.xbchat.top/#/auth
> 
> ![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/528b394f-d808-44c4-957a-897a783a7cb7)
> 
> 你可以看看数据库里面的RegisterCode表单有没有生成数据

**Comment by xiebiao99** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/666156f4-b03d-4365-850c-6dec5f49ac55)
有的，有验证码

**Comment by xiebiao99** [comment]
有的，有验证码的，登录成功了，可以了

**Comment by TPC-Light** [comment]
> 有的，有验证码的，登录成功了，可以了

我也登陆成功了

**Comment by TPC-Light** [comment]
> 有的，有验证码的，登录成功了，可以了

但是发信息是erro

**Comment by xiebiao99** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/463f0d6d-54be-43bc-a4c1-4e658350c59c)
对，不知道是为啥会这样啊

**Comment by xiebiao99** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/1c98b7c9-e335-43da-8e3d-91e09444a1f9)

**Comment by TPC-Light** [comment]
> ![image](https://user-images.githubusercontent.com/73516884/248188067-463f0d6d-54be-43bc-a4c1-4e658350c59c.png)
> 对，不知道是为啥会这样啊

OPENAI_BASE
OPENAI_KEY
这两个变量设置对没有

**Comment by xiebiao99** [comment]
设置对的 
OPENAI_BASE=https://api.openai.com
OPENAI_KEY=sk-YXU8mxxxxxxxxxxxxxxxxxxx

**Comment by TPC-Light** [comment]
> 设置对的 
> 
> OPENAI_BASE=https://api.openai.com
> 
> OPENAI_KEY=sk-YXU8mxxxxxxxxxxxxxxxxxxx

换个apikey试试

**Comment by TPC-Light** [comment]
> > 设置对的 
> > 
> > OPENAI_BASE=https://api.openai.com
> > 
> > OPENAI_KEY=sk-YXU8mxxxxxxxxxxxxxxxxxxx
> 
> 换个apikey试试

我搭这个没问题，也是今天才弄好![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/62536247/c1f084f5-e202-45f4-a726-02572a733abf)

**Comment by xiebiao99** [comment]
up的环境变量可以给个参考吗，你可以把关键信息替换为xxxxx，我就参考一下，比如微信登录的反代怎么设置的我也不会，
我重新部署了，但是有两处编译报错
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/707f0c36-b7b0-440d-b5ae-2fa93c512c5f)

**Comment by xiebiao99** [comment]
我记得刚开始用up的项目搭建成功的时候长这样
![Screenshot_2023-06-23-15-03-39-548_com tencent mt](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/3521acda-a67e-49ae-b19a-360d5c56bd81)
那时候邮箱可以登录，可以正常收发消息，还有支付套餐功能，现在最新版本的怎么退出重新登录呢

**Comment by TPC-Light** [comment]
> 我记得刚开始用up的项目搭建成功的时候长这样
> 
> ![Screenshot_2023-06-23-15-03-39-548_com tencent mt](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/3521acda-a67e-49ae-b19a-360d5c56bd81)
> 
> 那时候邮箱可以登录，可以正常收发消息，还有支付套餐功能，现在最新版本的怎么退出重新登录呢

没有看到退出登陆的按钮，只能清楚浏览器网站数据，或者开无痕浏览

老版的我没部署过

**Comment by TPC-Light** [comment]
> up的环境变量可以给个参考吗，你可以把关键信息替换为xxxxx，我就参考一下，比如微信登录的反代怎么设置的我也不会，
> 
> 我重新部署了，但是有两处编译报错
> 
> ![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/707f0c36-b7b0-440d-b5ae-2fa93c512c5f)
> 
> 

我也是小白，只弄了手机号和邮箱，部署也有报错![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/62536247/2ddcf821-4a6b-4213-be11-f401059552f8)

**Comment by xiebiao99** [comment]
好吧，那现在的这个怎么退出重新换其他方式登录呢，我好像找不到退出按钮；还有怎么设置微信登录的反向代理啊

**Comment by xiebiao99** [comment]
那你的微信登录可以成功登录吗

**Comment by TPC-Light** [comment]
> 那你的微信登录可以成功登录吗

微信认证要企业认证的公众号才行，我没弄

**Comment by TPC-Light** [comment]
> 好吧，那现在的这个怎么退出重新换其他方式登录呢，我好像找不到退出按钮；还有怎么设置微信登录的反向代理啊

开无痕浏览就行了

**Comment by xiebiao99** [comment]
好吧

**Comment by xch0911** [comment]
> 设置对的 OPENAI_BASE=https://api.openai.com OPENAI_KEY=sk-YXU8mxxxxxxxxxxxxxxxxxxx

最后怎么样？成功了吗？

**Comment by wym0913** [comment]
> > 那你的微信登录可以成功登录吗
> 
> 微信认证要企业认证的公众号才行，我没弄

·

**Comment by AprilNEA** [comment]
很抱歉，v2版本将不再维护，v3版本可关注 https://github.com/AprilNEA/ChatGPT-Admin-Web/releases/tag/v3.0.0-alpha
