### ISSUE TITLE
OPENAI_BASE=https://oa.api2d.net应该怎么设置啊

### ISSUE THREAD

**Issue by xiebiao99** [AprilNEA/ChatGPT-Admin-Web#109]
OPENAI_BASE=https://oa.api2d.net应该怎么设置啊
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/507b1b4e-3a6c-4c42-8a72-610efc048449)

**Comment by TPC-Light** [comment]
https://api.openai.com

**Comment by xiebiao99** [comment]
好的

**Comment by AprilNEA** [comment]
如果你不需要可以不填写。
