### ISSUE TITLE
邮箱Mailgun

### ISSUE THREAD

**Issue by LeeAirQ** [AprilNEA/ChatGPT-Admin-Web#11]
大佬可以把教程文档完善下吗？
1.mailgun是不是必须要付费35$才能用？那两个要求填的Key值和邮箱域名在那个页面可以找到
2.短信文档是空的

**Comment by AprilNEA** [comment]
1. 邮箱文档已更新 https://docs.lmo.best/docs/configuration/email
2. 请耐心等待文档发布。
