### ISSUE TITLE
Module not found: Can't resolve 'child_process' in Vercel Deployment

### ISSUE THREAD

**Issue by xiebiao99** [AprilNEA/ChatGPT-Admin-Web#110]
这个编译报错是怎么回事啊
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/aa44d93e-fc3e-42f6-90ff-00d69f55ddd3)

**Comment by TPC-Light** [comment]
最后部署成功了吗

**Comment by xiebiao99** [comment]
最后部署成功了，但是邮件服务注册和登录不了
