### ISSUE TITLE
migration.sql这个sql文件需要先在云数据库里面执行吗后再在vercel里面部署吗

### ISSUE THREAD

**Issue by xiebiao99** [AprilNEA/ChatGPT-Admin-Web#111]
migration.sql这个sql文件需要先在云数据库里面执行吗后再在vercel里面部署吗
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/73516884/eaf7505a-5951-46f8-b1eb-0c3178e03d31)

**Comment by AprilNEA** [comment]
这是用来迁移的。
如果建立数据库表，在文档的本地部署中写的很清楚。

**Comment by xiebiao99** [comment]
好的，那我本地部署的时候执行turbo run build命令后显示命令不存在
