### ISSUE TITLE
uni-sms短信服务环境变量中的SMS_SERVICE=uni-sms吧

### ISSUE THREAD

**Issue by xiebiao99** [AprilNEA/ChatGPT-Admin-Web#113]
uni-sms短信服务环境变量中的SMS_SERVICE=uni-sms吧，为啥配置了uni-sms的AccessKey ID和AccessKey Secret后短信发送没反应啊，发送不了短信啊，环境变量里面的签名是uni-sms的AccessKey Secret吗

**Comment by hyongqi** [comment]
填uni

**Comment by xiebiao99** [comment]
ok了，得吃了
