### ISSUE TITLE
【请教】本地部署报错 [ ReferenceError: TransformStream is not defined ]

### ISSUE THREAD

**Issue by strivingwang** [AprilNEA/ChatGPT-Admin-Web#119]
![mstsc_QsgCQRowkt](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/21355112/c7293d23-7bca-4741-a13b-a850ae05b882)
**请问下，这个有什么解决方案呢，感谢！！**

**Comment by strivingwang** [comment]
![mstsc_d5t5a8giBQ](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/21355112/e8446446-8e30-4cbb-83d8-2fed92b25150)
补充下详细错误，有没有谁遇到呀，试过很多次卡住了

**Comment by omegacc91** [comment]
也遇到一样的问题，怎么解决的？

_chatgpt-admin-web:build: ReferenceError: TransformStream is not defined
chatgpt-admin-web:build:     at Object.28356 (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/app/api/bots/[model]/route.js:581:34)
chatgpt-admin-web:build:     at __webpack_require__ (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/webpack-runtime.js:25:43)
chatgpt-admin-web:build:     at Object.40285 (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/app/api/bots/[model]/route.js:717:28)
chatgpt-admin-web:build:     at __webpack_require__ (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/webpack-runtime.js:25:43)
chatgpt-admin-web:build:     at Object.14073 (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/app/api/bots/[model]/route.js:321:17)
chatgpt-admin-web:build:     at __webpack_require__ (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/webpack-runtime.js:25:43)
chatgpt-admin-web:build:     at Object.88583 (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/app/api/bots/[model]/route.js:415:14)
chatgpt-admin-web:build:     at __webpack_require__ (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/webpack-runtime.js:25:43)
chatgpt-admin-web:build:     at Module.62096 (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/app/api/bots/[model]/route.js:174:12)
chatgpt-admin-web:build:     at __webpack_require__ (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/webpack-runtime.js:25:43)_

**Comment by strivingwang** [comment]
> 

没有解决呀,  我是在ubuntu18.0系统中部署的，node 版本是16.x

**Comment by strivingwang** [comment]
> 也遇到一样的问题，怎么解决的？
> 
> _chatgpt-admin-web:build: ReferenceError: TransformStream is not defined chatgpt-admin-web:build: at Object.28356 (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/app/api/bots/[model]/route.js:581:34) chatgpt-admin-web:build: at **webpack_require** (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/webpack-runtime.js:25:43) chatgpt-admin-web:build: at Object.40285 (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/app/api/bots/[model]/route.js:717:28) chatgpt-admin-web:build: at **webpack_require** (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/webpack-runtime.js:25:43) chatgpt-admin-web:build: at Object.14073 (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/app/api/bots/[model]/route.js:321:17) chatgpt-admin-web:build: at **webpack_require** (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/webpack-runtime.js:25:43) chatgpt-admin-web:build: at Object.88583 (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/app/api/bots/[model]/route.js:415:14) chatgpt-admin-web:build: at **webpack_require** (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/webpack-runtime.js:25:43) chatgpt-admin-web:build: at Module.62096 (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/app/api/bots/[model]/route.js:174:12) chatgpt-admin-web:build: at **webpack_require** (/home/omegacc/work/ChatGPT-Admin-Web/apps/chat/.next/server/webpack-runtime.js:25:43)_

没有解决呀, 我是在ubuntu18.0系统中部署的，node 版本是16.x

**Comment by gtihublg** [comment]
这个问题解决了吗

**Comment by strivingwang** [comment]
> 这个问题解决了吗

没有呀，卡在这里了

**Comment by circle-hotaru** [comment]
node 使用 v18 就好了

**Comment by AprilNEA** [comment]
@strivingwang 问题是否通过更新 Node 版本解决？

**Comment by strivingwang** [comment]
> @strivingwang 问题是否通过更新 Node 版本解决？
解决了，就是node版本问题

**Comment by larkinwang20** [comment]
> @strivingwang 问题是否通过更新 Node 版本解决？

解决了，就是node版本问题

**Comment by larkinwang20** [comment]
> 



> node 使用 v18 就好了

感谢，正解！
