### ISSUE TITLE
本地部署 turbo run遇到问题：We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023

### ISSUE THREAD

**Issue by byYufeng** [AprilNEA/ChatGPT-Admin-Web#120]
(node:32004) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

请问该如何解决

**Comment by AprilNEA** [comment]
能否给出相关截图，这不像是本项目的报错

**Comment by byYufeng** [comment]
<img width="1260" alt="image" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/11935877/1177c72b-6e6c-4697-9916-cf7af0ff12ae">

**Comment by byYufeng** [comment]
node版本：v16.20.0

**Comment by byYufeng** [comment]
> 
排查发现是npm install turbo-cli的问题

请问作者能否告知turbo的安装方式？ @AprilNEA

**Comment by Foxisnotfucks** [comment]
> node版本：v16.20.0/v18 猜测像是因为引入的某个module的问题？

您好，请问解决了吗

**Comment by takakie** [comment]
这是由于turbo本身的问题，我也遇到了。
解决办法是将turbo卸载了，重新安装。
npm uninstall -g turbo
npm cache clean --force
npm install -g turbo
OK

**Comment by byYufeng** [comment]
> > node版本：v16.20.0/v18 猜测像是因为引入的某个module的问题？
> 
> 您好，请问解决了吗

turbo版本的问题，使用了turbo-cli导致的

**Comment by AprilNEA** [comment]
> > node版本：v16.20.0/v18 猜测像是因为引入的某个module的问题？
> 
> 您好，请问解决了吗

出现了同学的问题？

> turbo版本的问题，使用了turbo-cli导致的

该问题在更新 turbo 版本后任然出现？
