### ISSUE TITLE
项目不错、几个具体模块抽象出来就更好了

### ISSUE THREAD

**Issue by youqiang95** [AprilNEA/ChatGPT-Admin-Web#121]
很不错的项目，如果database、登录鉴权、支付这几个模块抽象出来就更好了，大家可以用自己熟悉的方案很快实现和拓展，现在和一些具体的实现绑定的太紧了，如prisma、第三方登录和支付接口（虎皮椒）、鉴权方式（JWT）、数据库表的模型设计、文本过滤等。抽象出来之后，因为不涉及某些具体实现，很容易放一个demo出来，增加 stars数。（不过如果想提供直接可以营销的产品，那也没毛病）

**Comment by AprilNEA** [comment]
确实是个好想法，但是工程量可能有点大
