### ISSUE TITLE
How to access admin dashboard? 

### ISSUE THREAD

**Issue by imabutahersiddik** [AprilNEA/ChatGPT-Admin-Web#127]
I deployed one instance successfully but unable to login and create account and can't even access dashboard.
Can you please tell me how to access admin dashboard?

**Comment by AprilNEA** [comment]
> I deployed one instance successfully but unable to login and create account and can't even access dashboard. Can you please tell me how to access admin dashboard?

Sorry, the backend panel is being planned to be open source, I will give you news this week!
