### ISSUE TITLE
初始化数据库这块有没有什么别的方法，一直失败

### ISSUE THREAD

**Issue by biderpan-ai** [AprilNEA/ChatGPT-Admin-Web#130]
Tasks:    0 successful, 4 total
Cached:    0 cached, 4 total
  Time:    2.93s
Failed:    @caw/database#db:generate

 ERROR  run failed: command  exited (1)

**Comment by leoleelxh** [comment]
我是直接在数据库api文件中，替换成实际地址成功的

**Comment by byYufeng** [comment]
> 

请教下是本地部署吗 如何安装依赖 文档里没写 我这一直报错

**Comment by AprilNEA** [comment]
> > 
> 
> 请教下是本地部署吗 如何安装依赖 文档里没写 我这一直报错

仓库根目录 pnpm build 后 pnpm dev 可运行。
稍后会针对本地部署做出优化和文档不全。

**Comment by macshion** [comment]
> 

可以具体说下操作步骤吗？
