### ISSUE TITLE
本地部署 turbo run build持续报错

### ISSUE THREAD

**Issue by byYufeng** [AprilNEA/ChatGPT-Admin-Web#131]
package.json和文档中豆没有看到dependencies的列表，只看到中devDependencies有个turbo

安装turbo后turbo run build后持续报错
@caw/database:db:generate: ERROR: command finished with error: exec: "pnpm": executable file not found in $PATH

npm install pnpm后又出现
@caw/types:build: sh: tsc: not found

npm install typescript -g后
@caw/database:db:generate: sh: prisma: not found

对node不太熟 感觉应该是没有安装所需依赖的原因？
后来通过搜索发现/app/chat中有package.json，
npm install 报错：
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

yarn install 也报错：
error Workspaces can only be enabled in private projects.

请问如何解决？

**Comment by AprilNEA** [comment]
没有正确安装 pnpm, 可参考官方文档https://pnpm.io/
