### ISSUE TITLE
Object literal may only specify known properties, and 'plan' does not exist in type 'OrderCreateInput'.

### ISSUE THREAD

**Issue by Erik11571** [AprilNEA/ChatGPT-Admin-Web#132]
本人小白，尝试在本地部署。但有个模块一直报错了。请大佬帮忙指点下。谢谢！
使用系统:Linux b2 5.10.0-23-cloud-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux

具体报错如下:
root@b2:~/ChatGPT-Admin-Web# turbo run build
• Packages in scope: @caw/bots, @caw/dal, @caw/database, @caw/migration, @caw/ratelimit, @caw/types, chatgpt-admin-web, database-old, tsconfig
• Running build in 9 packages
• Remote caching disabled
@caw/database:db:generate: cache bypass, force executing 009dc2dbb13519c0
@caw/types:build: cache hit (outputs already on disk), replaying logs 4780d76861e3e77d
@caw/types:build: 
@caw/types:build: > @caw/types@0.0.1 build /root/ChatGPT-Admin-Web/packages/types
@caw/types:build: > tsc --build
@caw/types:build: 
@caw/bots:build: cache hit (outputs already on disk), replaying logs 48f61e2f03987753
@caw/bots:build: 
@caw/bots:build: > @caw/bots@0.0.1 build /root/ChatGPT-Admin-Web/packages/bots
@caw/bots:build: > tsc --build
@caw/bots:build: 
database-old:build: cache hit (outputs already on disk), replaying logs 1582febea0ba8ec8
database-old:build: 
database-old:build: > database-old@0.0.1 build /root/ChatGPT-Admin-Web/packages/database-old
database-old:build: > tsc --build
database-old:build: 
@caw/database:db:generate: 
@caw/database:db:generate: > @caw/database@0.0.1 db:generate /root/ChatGPT-Admin-Web/packages/database
@caw/database:db:generate: > prisma generate --schema=./prisma/schema.prisma
@caw/database:db:generate: 
@caw/database:db:generate: Prisma schema loaded from prisma/schema.prisma
@caw/database:db:generate: 
@caw/database:db:generate: ✔ Generated Prisma Client (4.15.0 | library) to ./../../node_modules/.pnpm/@prisma+client@4.15.0_prisma@4.15.0/node_modules/@prisma/client in 628ms
@caw/database:db:generate: You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
@caw/database:db:generate: ```
@caw/database:db:generate: import { PrismaClient } from '@prisma/client'
@caw/database:db:generate: const prisma = new PrismaClient()
@caw/database:db:generate: ```
@caw/ratelimit:build: cache hit (outputs already on disk), replaying logs 315b7188a18954e5
@caw/ratelimit:build: 
@caw/ratelimit:build: > @caw/ratelimit@0.0.1 build /root/ChatGPT-Admin-Web/packages/caw-ratelimit
@caw/ratelimit:build: > tsc --build
@caw/ratelimit:build: 
@caw/dal:build: cache miss, executing efb05a669eaba68a
@caw/dal:build: 
@caw/dal:build: > @caw/dal@0.0.1 build /root/ChatGPT-Admin-Web/packages/dal
@caw/dal:build: > tsc --build
@caw/dal:build: 
@caw/dal:build: src/dal/order.ts(36,7): error TS2322: Type '{ orderId: string; count: number; amount: number; status: "Pending"; plan: { connect: { planId: number; }; }; price: { connect: { id: number; }; }; user: { connect: { userId: number; }; }; }' is not assignable to type 'OrderCreateInput'.
@caw/dal:build:   Object literal may only specify known properties, and 'plan' does not exist in type 'OrderCreateInput'.
@caw/dal:build: src/dal/order.ts(82,28): error TS2339: Property 'planId' does not exist on type 'Order & { price: Prices; }'.
@caw/dal:build: src/dal/plan.ts(10,5): error TS2322: Type 'import("/root/ChatGPT-Admin-Web/node_modules/.pnpm/@prisma+client@4.15.0_prisma@4.15.0/node_modules/.prisma/client/index").Plan[]' is not assignable to type 'import("/root/ChatGPT-Admin-Web/packages/types/dist/dal").DALType.Plan[]'.
@caw/dal:build:   Type 'Plan' is missing the following properties from type 'Plan': prices, limits
@caw/dal:build: src/dal/plan.ts(28,9): error TS2322: Type '{ prices: { select: { id: true; name: true; amount: true; duration: true; }; }; limits: { select: { modelName: true; times: true; duration: true; }; }; orders: false; redeems: false; subscriptions: false; }' is not assignable to type 'PlanInclude'.
@caw/dal:build:   Object literal may only specify known properties, and 'orders' does not exist in type 'PlanInclude'.
@caw/dal:build: src/utils/startup.ts(48,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build: src/utils/startup.ts(54,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build: src/utils/startup.ts(60,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build: src/utils/startup.ts(66,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build: src/utils/startup.ts(72,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build: src/utils/startup.ts(78,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build:  ELIFECYCLE  Command failed with exit code 1.
@caw/dal:build: ERROR: command finished with error: command (/root/ChatGPT-Admin-Web/packages/dal) pnpm run build exited (1)
command (/root/ChatGPT-Admin-Web/packages/dal) pnpm run build exited (1)

 Tasks:    5 successful, 6 total
Cached:    4 cached, 6 total
  Time:    8.047s 
Failed:    @caw/dal#build

**Comment by fiyen** [comment]
解决了吗？我也是小白，也是这个错误。。。

**Comment by Erik11571** [comment]
还没解决，估计是数据库连接的问题。
我现在转到了另一个差不多的项目了。
https://github.com/Nanjiren01/AIChatWeb
不过这个项目admin的部分不是开源的。
另外，你有兴趣的话可以加群Q304135945一起交流学习。


WinSun ***@***.***> 于 2023年7月18日周二 04:13写道：

**Comment by iszcz** [comment]
一只这样，有没有大佬说明下是什么情况

**Comment by AprilNEA** [comment]
The issue is being followed up and news is expected this week

**Comment by AprilNEA** [comment]
v2版本将不再维护，v3版本可关注 https://github.com/AprilNEA/ChatGPT-Admin-Web/releases/tag/v3.0.0-alpha
