### ISSUE TITLE
已在本地 vercel部署完成，使用过程一些bug提交，望大佬翻牌

### ISSUE THREAD

**Issue by WSL12131415** [AprilNEA/ChatGPT-Admin-Web#133]
bug1 使用gpt 4-0314 ，gpt4-32k ，gpt3-16k 报错， 在yidada大佬的源码上是可以用的，😅😅
<img width="1432" alt="截屏2023-07-31 01 02 57" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/121419347/2b97eb49-890d-47f6-868b-8fc1bebd2ebd">
<img width="1432" alt="截屏2023-07-31 01 07 43" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/121419347/662f95f4-7780-41ef-aaa5-93dddae83ec1">
      2 neon邮箱验证码发送成功，但是在gmail中看不到，燃鹅在数据库中能找到code验证码
<img width="1432" alt="截屏2023-07-31 01 20 02" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/121419347/d36d8a8e-6d37-407b-95cc-f9dc301c92b4">

      3 个人主页空白😅😅
<img width="1432" alt="截屏2023-07-31 01 18 40" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/121419347/7db00aff-cdb3-42c6-9628-ceca27ad33db">

**Comment by AprilNEA** [comment]
以上bug均在v3中解决。
