### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by MaxwellEdisons** [AprilNEA/ChatGPT-Admin-Web#136]
@/app/hooks/use-prevent-form
@/app/lib/wechat

**Comment by AprilNEA** [comment]
There may have been an error during the master branch merge, it will be fixed as soon as possible

**Comment by MaxwellEdisons** [comment]
extremely grateful

**Comment by WSL12131415** [comment]
感激大佬 ，

**Comment by WSL12131415** [comment]
/
![微信截图_20230802024524](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/121419347/fd115428-daf2-4c89-82c5-cfa909763194)

**Comment by WSL12131415** [comment]
![微信截图_20230802024524](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/121419347/b52701c8-58b0-4f82-a20b-b5f115d1d5a3)
出现这个报错  好像是数据库的问题

**Comment by WSL12131415** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/121419347/737b67c3-c874-4289-a3c5-2c80e017e374)

**Comment by AprilNEA** [comment]
很抱歉，v2版本将不再维护，v3版本可关注 https://github.com/AprilNEA/ChatGPT-Admin-Web/releases/tag/v3.0.0-alpha
