### ISSUE TITLE
$ pnpm build  > chatgpt-admin-web@1.0.0 build C:\Users\xxx\ChatGPT-Admin-Web > turbo run build  (node:19552) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.  Please migrate your code to use AWS SDK for JavaScript (v3). For more information, check the migration guide at https://a.co/7PzMCcy (Use `node --trace-warnings ...` to show where the warning was created)

### ISSUE THREAD

**Issue by macshion** [AprilNEA/ChatGPT-Admin-Web#138]
本地build会报这个错，怎么处理呢？

`$ pnpm build

> chatgpt-admin-web@1.0.0 build C:\Users\xxx\ChatGPT-Admin-Web
> turbo run build

(node:19552) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)`

**Comment by AprilNEA** [comment]
很抱歉，v2版本将不再维护，v3版本可关注 https://github.com/AprilNEA/ChatGPT-Admin-Web/releases/tag/v3.0.0-alpha
