### ISSUE TITLE
本地部署，执行这个命令turbo run build这个错误

### ISSUE THREAD

**Issue by Rs529811807** [AprilNEA/ChatGPT-Admin-Web#139]
@caw/dal:build: src/startup.ts(2,15): error TS2305: Module '"@prisma/client"' has no exported member 'Role'.
@caw/dal:build:  ELIFECYCLE  Command failed with exit code 1.
@caw/dal:build: ERROR: command finished with error: command (C:\Users\Administrator\Downloads\ChatGPT-Admin-Web-main\packages\dal) pnpm run build exited (1)
@caw/dal#build: command (C:\Users\Administrator\Downloads\ChatGPT-Admin-Web-main\packages\dal) pnpm run build exited (1)

 Tasks:    4 successful, 5 total
Cached:    3 cached, 5 total
  Time:    10.326s
Failed:    @caw/dal#build

 ERROR  run failed: command  exited (1)

**Comment by AprilNEA** [comment]
很抱歉，v2版本将不再维护，v3版本可关注 https://github.com/AprilNEA/ChatGPT-Admin-Web/releases/tag/v3.0.0-alpha
