### ISSUE TITLE
手机，邮箱验证码获取失败 ，所有环境变量已经部署

### ISSUE THREAD

**Issue by WSL12131415** [AprilNEA/ChatGPT-Admin-Web#140]
手机，邮箱验证码获取失败 ，所有环境变量已经部署，数据库 已经链接
<img width="494" alt="WX20230808-172310@2x" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/121419347/8afe0ea9-7430-467b-98d7-b0727f626990">

**Comment by AprilNEA** [comment]
邮箱用的是什么

**Comment by wsl622813** [comment]
> 邮箱用的是什么
大佬你好！ 我用的是.elasticemail  然后用vercel 部署   数据库用的是neon

**Comment by wsl622813** [comment]
@AprilNEA 大佬你好！ 我用.elasticemail 然后用 vercel 部署数据库用的是 neon   

用之前版本，是可以收到邮箱验证码，但是验证码只存在neon数据库，邮箱收不到验证码

**Comment by wsl622813** [comment]
抱歉 是我在neon链接的数据库 与之前项目冲突了  现在可以了 但是邮箱依然收不到验证码  只能在数据库查看

**Comment by AprilNEA** [comment]
很抱歉，v2版本将不再维护，v3版本可关注 https://github.com/AprilNEA/ChatGPT-Admin-Web/releases/tag/v3.0.0-alpha
