### ISSUE TITLE
执行 build 报一系列类型相关的错误

### ISSUE THREAD

**Issue by baifuyou** [AprilNEA/ChatGPT-Admin-Web#141]
@caw/dal:build: src/dal/order.ts(36,7): error TS2322: Type '{ orderId: string; count: number; amount: number; status: "Pending"; plan: { connect: { planId: number; }; }; price: { connect: { id: number; }; }; user: { connect: { userId: number; }; }; }' is not assignable to type 'OrderCreateInput'.
@caw/dal:build:   Object literal may only specify known properties, and 'plan' does not exist in type 'OrderCreateInput'.
@caw/dal:build: src/dal/order.ts(82,28): error TS2339: Property 'planId' does not exist on type 'Order & { price: Prices; }'.
@caw/dal:build: src/dal/plan.ts(10,5): error TS2322: Type 'import("/Users/baifuyou/NodeWorks/ChatGPT-Admin-Web/node_modules/.pnpm/@prisma+client@4.15.0_prisma@4.15.0/node_modules/.prisma/client/index").Plan[]' is not assignable to type 'import("/Users/baifuyou/NodeWorks/ChatGPT-Admin-Web/packages/types/dist/dal").DALType.Plan[]'.
@caw/dal:build:   Type 'Plan' is missing the following properties from type 'Plan': prices, limits
@caw/dal:build: src/dal/plan.ts(28,9): error TS2322: Type '{ prices: { select: { id: true; name: true; amount: true; duration: true; }; }; limits: { select: { modelName: true; times: true; duration: true; }; }; orders: false; redeems: false; subscriptions: false; }' is not assignable to type 'PlanInclude'.
@caw/dal:build:   Object literal may only specify known properties, and 'orders' does not exist in type 'PlanInclude'.
@caw/dal:build: src/utils/startup.ts(48,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build: src/utils/startup.ts(54,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build: src/utils/startup.ts(60,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build: src/utils/startup.ts(66,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build: src/utils/startup.ts(72,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build: src/utils/startup.ts(78,7): error TS2741: Property 'isCurrent' is missing in type '{ name: string; amount: number; duration: number; planId: number; }' but required in type 'PricesCreateManyInput'.
@caw/dal:build:  ELIFECYCLE  Command failed with exit code 1.
@caw/dal:build: ERROR: command finished with error: command (/Users/baifuyou/NodeWorks/ChatGPT-Admin-Web/packages/dal) pnpm run build exited (1)

**Comment by AprilNEA** [comment]
很抱歉，v2版本将不再维护，v3版本可关注 https://github.com/AprilNEA/ChatGPT-Admin-Web/releases/tag/v3.0.0-alpha
