### ISSUE TITLE
文档链接不可访问

### ISSUE THREAD

**Issue by PeanutSplash** [AprilNEA/ChatGPT-Admin-Web#143]
https://caw.sku.moe/打不开了

**Comment by AprilNEA** [comment]
文档正在做迁移，如果想查看v3版本文档可访问 [aprilnea.mintlify.app](https://aprilnea.mintlify.app)

**Comment by liron-li** [comment]
[aprilnea.mintlify.app](https://aprilnea.mintlify.app/) 这个也打不开，还有其他地址吗
