### ISSUE TITLE
Next.js 如何修复 ERR_PNPM_OUTDATED_LOCKFILE？

### ISSUE THREAD

**Issue by huaxianhu** [AprilNEA/ChatGPT-Admin-Web#144]
当我将项目部署到 Vercel 时，构建失败并出现以下错误：

ERR_PNPM_OUTDATED_LOCKFILE 无法使用“frozen-lockfile”安装，因为 pnpm-lock.yaml 与 package.json 不是最新的
这是什么意思以及如何解决它？

**Comment by AprilNEA** [comment]
对于不再维护的 v1 版本，您可以在本地克隆您自己的 fork 仓库，在安装了 Nodejs 环境的前提下，删除 pnpm-lock.yaml 文件，重新运行 pnpm install。
