### ISSUE TITLE
PrismaClientInitializationError after docker composed

### ISSUE THREAD

**Issue by SantoshKumarRavi** [AprilNEA/ChatGPT-Admin-Web#147]
i followed the official documentation. 
still i cannot over come this issue.
any fix ?
![Screenshot (1105)](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/105963429/f03f8612-f0a7-48c4-b6bf-77aa582d7ed9)

**Comment by AprilNEA** [comment]
I'll follow up on this and get back to you by tomorrow at the latest.

**Comment by AprilNEA** [comment]
If things are very urgent, you can try installing the dependencies manually and then running pnpx prisma db push in the apps/server directory.

**Comment by SantoshKumarRavi** [comment]
ok. thanks in advance.
and another issue is i run backend as separate service using `npm run start:dev`.
i attached the issue in video.
i dont know why server is broken without any errors .




https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/105963429/d287d07f-ab89-429b-b39b-cb51fb3aae09

**Comment by SantoshKumarRavi** [comment]
yes. just seen the translation of it 数据库设置有误.
database settings are wrong

**Comment by SantoshKumarRavi** [comment]
`turbo run build working fine .
`
![Screenshot (1106)](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/105963429/20b6ce8c-9757-4870-8f5d-f2a329306ebe)

`but turbo run start has some errors like modules not found and has-flag issue
`

![Screenshot (1107)](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/105963429/ef96e888-3e76-4ef7-ae58-73e72d80aaa5)

**Comment by ohmyskyhigh** [comment]
> yes. just seen the translation of it 数据库设置有误. database settings are wrong

This is likely caused by Redis setting

**Comment by SantoshKumarRavi** [comment]
@AprilNEA  manual set up done for front end and backend ,
can u figure out  prismaClientinitialError issue in backend dockerfile?

any documentation available backend flow ?

**Comment by ohmyskyhigh** [comment]
Reference from this issue: https://github.com/prisma/prisma/discussions/20257

Maybe try to use pnpm run start:dev instead of building the bundle

**Comment by AprilNEA** [comment]
> Reference from this issue: [prisma/prisma#20257](https://github.com/prisma/prisma/discussions/20257)
> 
> Maybe try to use pnpm run start:dev instead of building the bundle

Does this work?

**Comment by SantoshKumarRavi** [comment]
> > Reference from this issue: [prisma/prisma#20257](https://github.com/prisma/prisma/discussions/20257)
> > Maybe try to use pnpm run start:dev instead of building the bundle
> 
> Does this work?

development it is working fine with change in server-dockr-file

```
RUN pnpx turbo run db:generate 
CMD pnpx turbo run start
```

**Comment by SantoshKumarRavi** [comment]
@AprilNEA 
Problem is that schema is not copied in dist folder of production build
i resolved this by these trial and error methods. i know one of the methods only correct.

```
COPY --from=builder /app/apps/server/prisma/ ./apps/server/dist/prisma
COPY --from=builder /app/apps/server/prisma/ ./prisma
COPY --from=builder /app/apps/server/prisma/ ./server/dist/prisma
COPY --from=builder /app/apps/server/prisma/ ./apps/prisma
COPY --from=builder /app/apps/server/prisma/ ./apps/server/dist/prisma
```

but now npx migrate error  while using `npx prisma migate deploy`
https://stackoverflow.com/questions/67796217/prisma-getting-environment-variable-not-found-error-message-when-running-graph

and i tried  without this also.
```
[Redis] Module Init
数据库设置有误 Can't reach database server at `localhost`:`5432`
Please make sure your database server is running at `localhost`:`5432`.
```
i also tried by changing localhost->redis and localhost->postgres.
Got the same error.
any idea ?

**Comment by SantoshKumarRavi** [comment]
```
RUN pnpx turbo run db:generate \
    & pnpx turbo run build
    
WORKDIR /app/apps/server

CMD npx prisma migrate deploy && node /app/apps/server/dist/main.js
```
along with documentation
https://turbo.build/repo/docs/handbook/tools/prisma

yes . this works without crash
@AprilNEA  @ohmyskyhigh 

[screen-capture (5).webm](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/105963429/dd3af3d5-0c82-47fe-9ad9-0e9182d8002b)

**Comment by SantoshKumarRavi** [comment]
how can i make PR for this ?
got access denied.

![Screenshot (1118)](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/105963429/2d0c2ab6-c010-4c66-9124-03d4199e73d0)

**Comment by AprilNEA** [comment]
> how can i make PR for this ? got access denied.
> 
> ![Screenshot (1118)](https://user-images.githubusercontent.com/105963429/268496502-2d0c2ab6-c010-4c66-9124-03d4199e73d0.png)

You can fork and then raise PR

**Comment by SantoshKumarRavi** [comment]
@AprilNEA 
PR made 
https://github.com/AprilNEA/ChatGPT-Admin-Web/pull/151

**Comment by SantoshKumarRavi** [comment]
https://github.com/AprilNEA/ChatGPT-Admin-Web/pull/153

merged
