### ISSUE TITLE
server:start: The table `public.Model` does not exist in the current database.

### ISSUE THREAD

**Issue by GreatAsia** [AprilNEA/ChatGPT-Admin-Web#156]
我的执行步骤是：
1 根目录设置 config.yaml 
2 根目录执行 pnpm install
3 再执行turbo run build
4 再执行 turbo run start

这四个步骤，不知道中间少步骤没有

运行 turbo run start
报错
                                                                                  ^
server:start: PrismaClientKnownRequestError:
server:start: Invalid `prisma.model.findMany()` invocation:
server:start: 
server:start: 
server:start: The table `public.Model` does not exist in the current database.
server:start:     at Hr.handleRequestError (E:\AIProject\ChatGPT-Admin-Web\apps\server\dist\main.js:1058:6999)
server:start:     at Hr.handleAndLogRequestError (E:\AIProject\ChatGPT-Admin-Web\apps\server\dist\main.js:1058:6388)
server:start:     at Hr.request (E:\AIProject\ChatGPT-Admin-Web\apps\server\dist\main.js:1058:6108)
server:start:     at l (E:\AIProject\ChatGPT-Admin-Web\apps\server\dist\main.js:1062:10298)
server:start:     at E:\AIProject\ChatGPT-Admin-Web\apps\server\dist\main.js:378:24
server:start:     at Proxy._transactionWithCallback (E:\AIProject\ChatGPT-Admin-Web\apps\server\dist\main.js:1062:8971)
server:start:  ELIFECYCLE  Command failed with exit code 1.
server:start: ERROR: command finished with error: command (E:\AIProject\ChatGPT-Admin-Web\apps\server) pnpm run start exited (1)

**Comment by AprilNEA** [comment]
1. 拉去最新的`v3`分支
2. 正确环境配置下运行 `pnpm run db:init`
