### ISSUE TITLE
unable to resolve dependency tree  

### ISSUE THREAD

**Issue by CXK6013** [AprilNEA/ChatGPT-Admin-Web#159]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: backend@undefined
npm ERR! Found: @nestjs/common@10.2.8
npm ERR! node_modules/@nestjs/common
npm ERR!   @nestjs/common@"^10.0.0" from backend@undefined
npm ERR!   packages/backend
npm ERR!     backend@undefined
npm ERR!     node_modules/backend
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by CXK6013** [comment]
这个依赖去哪里找，还是我没认真看文档

**Comment by AprilNEA** [comment]
请在根目录使用`pnpm install`，如未安装pnpm请先`npm install pnpm -g`.
