### ISSUE TITLE
找不到 config.example.yaml

### ISSUE THREAD

**Issue by caicaicai** [AprilNEA/ChatGPT-Admin-Web#163]
帮助文档让 cp config.example.yaml config.yaml ，但是项目里面并没有找到config.example.yaml 这个文件

**Comment by caicaicai** [comment]
似乎是 6d3a044fe002707d9f5e132f5f796f1a46827627 这次提交被移除了

**Comment by antiwar3** [comment]
他改成用config.json了，然后这个玩意没穿

**Comment by 1-bytes** [comment]
我也遇到这个问题了
目前看来 config.example.yaml 被删了，改用 config.json 了
但是 config.json 作者可能忘记传上来了

有大佬蹲到后续或者解决了踢我一脚哈，感谢！

@AprilNEA

**Comment by y22emc2** [comment]
有什么临时解决的办法吗

**Comment by 1-bytes** [comment]
> 有什么临时解决的办法吗

没办法，我现在特别想用也没法部署，等作者更新。

**Comment by mmw1984** [comment]
@AprilNEA

**Comment by AprilNEA** [comment]
请拉取最新版本并参考最新的文档进行部署：https://manual.sku.moe/project/chatgpt-admin-web/quickstart
