### ISSUE TITLE
[ENG-51] Pnpm unmet peer with monorepo package

### ISSUE THREAD

**Issue by AprilNEA** [AprilNEA/ChatGPT-Admin-Web#168]
```
# pnpm install

Scope: all 5 workspace projects

WARN  2 deprecated subdependencies found: sourcemap-codec@1.4.8, stable@0.1.8

Already up to date

Progress: resolved 1257, reused 1243, downloaded 0, added 0, done

WARN  Issues with peer dependencies found

packages/backend

├─┬ nestjs-prisma 0.22.0

│ └── ✕ unmet peer @prisma/client@@nest-http/prisma@*: found undefined

└─┬ prisma-extension-pagination 0.5.0

└── ✕ unmet peer @prisma/client@"^4.9.0 || ^5.0.0": found undefined

Done in 8.9s
```

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-51](https://linear.app/interlink/issue/ENG-51/pnpm-unmet-peer-with-monorepo-package)</sub>

**Comment by Ray2310** [comment]
I also have the same error, when executing pnpm run db:init
The error message is as follows:
```
✔ Generated Prisma Client (v5.3.1) to ./prisma/client in 305ms

Running seed command `ts-node prisma/seed.ts` ...
PrismaClientKnownRequestError: 
Invalid `prisma.model.createMany()` invocation in
/root/ChatGPT-Admin-Web/prisma/seed.ts:6:37

  3 const prisma = new PrismaClient();
  4 
  5 async function main() {
→ 6   const models = await prisma.model.createMany(
Unique constraint failed on the fields: (`id`)
    at wn.handleRequestError (/root/ChatGPT-Admin-Web/prisma/client/runtime/library.js:123:6730)
    at wn.handleAndLogRequestError (/root/ChatGPT-Admin-Web/prisma/client/runtime/library.js:123:6119)
    at wn.request (/root/ChatGPT-Admin-Web/prisma/client/runtime/library.js:123:5839)
    at async l (/root/ChatGPT-Admin-Web/prisma/client/runtime/library.js:128:9763)
    at async main (/root/ChatGPT-Admin-Web/prisma/seed.ts:6:18) {
  code: 'P2002',
  clientVersion: '5.3.1',
  meta: { target: [ 'id' ] }
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed.ts
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by AprilNEA** [comment]
@Ray2310 Are you using a database that already has tables or data created? Please retry with a completely new database. Please re-open an issue if the problem persists.

**Comment by Ray2310** [comment]
> @Ray2310 Are you using a database that already has tables or data created? Please retry with a completely new database. Please re-open an issue if the problem persists.

The database has been created, but the problem still exists

**Comment by lecleeV** [comment]
I encountered the same problem. Is there a solution for this situation now?

**Comment by CaptainTomSparta** [comment]
same issue  appeared（im rookie for mono repo）
1.pnpm install :indicate 【deprecated subdependencies found: sourcemap-codec@1.4.8, stable@0.1.8】
2.postgresql  init：【correct】
2.turbo run start :indicate【Error: ENOENT: no such file or directory, open 'D:\Workspace-test\ChatGPT-Admin-Web\packages\frontend\.next\BUILD_ID'] 】【?[91m?[1;31;7m ERROR ?[0m?[31m run failed: command  exited (1)?[0m?[0m】
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/48318680/c895dcd2-1963-43d8-a02f-ce4e8557ca88)

**Comment by AprilNEA** [comment]
@CaptainTomSparta @iamastudentlo @Ray2310 Let's follow up on this in #171
