### ISSUE TITLE
[ENG-53] An error occurred while running the seed command

### ISSUE THREAD

**Issue by AprilNEA** [AprilNEA/ChatGPT-Admin-Web#171]
[https://github.com/AprilNEA/ChatGPT-Admin-Web/issues/168#issuecomment-1836296358](https://github.com/AprilNEA/ChatGPT-Admin-Web/issues/168#issuecomment-1836296358)
[https://github.com/AprilNEA/ChatGPT-Admin-Web/issues/168#issuecomment-1837409274](https://github.com/AprilNEA/ChatGPT-Admin-Web/issues/168#issuecomment-1837409274)

```
✔ Generated Prisma Client (v5.3.1) to ./prisma/client in 305ms

Running seed command `ts-node prisma/seed.ts` ...
PrismaClientKnownRequestError: 
Invalid `prisma.model.createMany()` invocation in
/root/ChatGPT-Admin-Web/prisma/seed.ts:6:37

  3 const prisma = new PrismaClient();
  4 
  5 async function main() {
→ 6   const models = await prisma.model.createMany(
Unique constraint failed on the fields: (`id`)
    at wn.handleRequestError (/root/ChatGPT-Admin-Web/prisma/client/runtime/library.js:123:6730)
    at wn.handleAndLogRequestError (/root/ChatGPT-Admin-Web/prisma/client/runtime/library.js:123:6119)
    at wn.request (/root/ChatGPT-Admin-Web/prisma/client/runtime/library.js:123:5839)
    at async l (/root/ChatGPT-Admin-Web/prisma/client/runtime/library.js:128:9763)
    at async main (/root/ChatGPT-Admin-Web/prisma/seed.ts:6:18) {
  code: 'P2002',
  clientVersion: '5.3.1',
  meta: { target: [ 'id' ] }
}

An error occurred while running the seed command:
Error: Command failed with exit code 1: ts-node prisma/seed.ts
 ELIFECYCLE  Command failed with exit code 1.
```

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-53](https://linear.app/interlink/issue/ENG-53/an-error-occurred-while-running-the-seed-command)</sub>

**Comment by AprilNEA** [comment]
@iamastudentlo @Ray2310 @CaptainTomSparta
I hava a problem that may need your help:
Any data exists in your database tables such as `Model` table, before and after failing to run `pnpm run db:init` ?

**Comment by Ray2310** [comment]
> @iamastudentlo @Ray2310 @CaptainTomSparta I hava a problem that may need your help: Any data exists in your database tables such as `Model` table, before and after failing to run `pnpm run db:init` ?

According to your installation steps, just quickly start a PostgreSQL database through Docker, then set the DATABASE_URL environment variable, and then run in the project root directory:`pnpm run db:init`.and no other operations

**Comment by lecleeV** [comment]
> @iamastudentlo @Ray2310 @CaptainTomSparta I hava a problem that may need your help: Any data exists in your database tables such as `Model` table, before and after failing to run `pnpm run db:init` ?

There is no database tables, and it has no influence to installing. It only misses the config.json file and a dependency named
@ant-design/cssinjs 1.18.0. After I add them. I make it. Here is the order `pnpm add @ant-design/cssinjs --workspace-root` 
[config.json](https://github.com/AprilNEA/ChatGPT-Admin-Web/files/13538813/config.json)

**Comment by CaptainTomSparta** [comment]
1.database itself look legit,(i quick peeked it after db:init，believed has no influence)【i installed postgresql-15.5-1-windows-x64】
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/48318680/39d67943-b135-41fa-bf75-af81662fed8d)
2.and 【config.json】does missing before, i put it under【ChatGPT-Admin-Web】，installed【pnpm add @ant-design/cssinjs --workspace-root】，then get errors by【chat.service.ts】
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/48318680/edce1445-0ba9-45a9-b3f4-bc883937ebd7)
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/48318680/499dd70f-b52d-4516-a128-1e0612483c28)

**Comment by ufoozhenghao** [comment]
遇到了同样的问题 pnpm install 后报依赖错误，db init没问题，start后报错。请问是否是node版本问题？
环境： 
  win11 
  node: v20.10.0
  docker desktop: Docker version 24.0.7, build afdd53b
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/42081344/fcd855d0-d6e1-4f1d-b472-b85a7f15a486)

根目录新建了 `.env`
```
DATABASE_URL=postgres://postgres:mypassword@localhost:5432/postgres
```
创建容器
```
docker run -itd --name caw -e POSTGRES_PASSWORD=mypassword-p 5432:5432 -d postgres
```

`pnpm run db:init`
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/42081344/e89da5d2-b508-45c8-91ea-70d64e439385)

`turbo run start`
```
$ turbo run start
• Packages in scope: @nest-http/prisma, backend, frontend, shared
• Running start in 4 packages
• Remote caching disabled
backend:start: cache miss, executing bedbf8e6af55f94f
frontend:start: cache miss, executing eaaef2a6d9402445
backend:start: 
backend:start: > backend@ start D:\ChatGPT-Admin-Web-3\packages\backend    
backend:start: > nest start
backend:start:
frontend:start:
frontend:start: > frontend@ start D:\ChatGPT-Admin-Web-3\packages\frontend 
frontend:start: > next start
frontend:start:
frontend:start: [Error: ENOENT: no such file or directory, open 'D:\ChatGPT-Admin-Web-3\packages\frontend\.next\BUILD_ID'] {
frontend:start:   errno: -4058,
frontend:start:   code: 'ENOENT',
frontend:start:   syscall: 'open',
frontend:start:   path: 'D:\\ChatGPT-Admin-Web-3\\packages\\frontend\\.next\\BUILD_ID'
frontend:start: }
frontend:start:  ELIFECYCLE  Command failed with exit code 1.
frontend:start: ERROR: command finished with error: command (D:\ChatGPT-Admin-Web-3\packages\frontend) pnpm run start exited (1)
backend:start: ERROR in ./src/common/config/config.service.ts:8:44
backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
backend:start:      6 | import { BizException } from '@/common/exceptions/biz.exception';
backend:start:      7 |
backend:start:   >  8 | import { ConfigType, ISettingSchema } from 'shared';
backend:start:        |                                            ^^^^^^^^
backend:start:      9 | import { ErrorCodeEnum } from 'shared/dist/error-code';
backend:start:     10 |
backend:start:     11 | const DEFAULT_CONFIG = {
backend:start:
backend:start: ERROR in ./src/common/config/config.service.ts:9:31
backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
backend:start:      7 |
backend:start:      8 | import { ConfigType, ISettingSchema } from 'shared';
backend:start:   >  9 | import { ErrorCodeEnum } from 'shared/dist/error-code';
backend:start:        |                               ^^^^^^^^^^^^^^^^^^^^^^^^
backend:start:     10 |
backend:start:     11 | const DEFAULT_CONFIG = {
backend:start:     12 |   mode: 'nginx',
backend:start:
backend:start: ERROR in ./src/common/exceptions/biz.exception.ts:3:31      
backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
backend:start:     1 | import { HttpException } from '@nestjs/common';     
backend:start:     2 |
backend:start:   > 3 | import { ErrorCodeEnum } from 'shared/dist/error-code';
backend:start:       |                               ^^^^^^^^^^^^^^^^^^^^^^^^
backend:start:     4 |
backend:start:     5 | export const ErrorCode = Object.freeze<
backend:start:     6 |   Record<ErrorCodeEnum, [string, string, number]>   
backend:start:
backend:start: ERROR in ./src/common/filters/all-execption.filter.ts:10:31 
backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
backend:start:      8 | } from '@nestjs/common';
backend:start:      9 |
backend:start:   > 10 | import { ErrorCodeEnum } from 'shared/dist/error-code';
backend:start:        |                               ^^^^^^^^^^^^^^^^^^^^^^^^
backend:start:     11 |
backend:start:     12 | @Catch()
backend:start:     13 | export class AllExceptionFilter implements ExceptionFilter {
backend:start:
backend:start: ERROR in ./src/common/guards/auth.guard.ts:14:31
backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
backend:start:     12 | import { JWTPayload, JwtService } from '@/libs/jwt/jwt.service';
backend:start:     13 |
backend:start:   > 14 | import { ErrorCodeEnum } from 'shared/dist/error-code';
backend:start:        |                               ^^^^^^^^^^^^^^^^^^^^^^^^
backend:start:     15 |
backend:start:     16 | export { Role } from '@prisma/client';
backend:start:     17 | export const ROLES_KEY = 'roles';
backend:start:
backend:start: ERROR in ./src/common/pipes/joi.ts:5:31
backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
backend:start:     3 | import { BizException } from '@/common/exceptions/biz.exception';
backend:start:     4 |
backend:start:   > 5 | import { ErrorCodeEnum } from 'shared/dist/error-code';
backend:start:       |                               ^^^^^^^^^^^^^^^^^^^^^^^^
backend:start:     6 |
backend:start:     7 | @Injectable()
backend:start:     8 | export class JoiValidationPipe implements PipeTransform {
backend:start:
backend:start: ERROR in ./src/libs/email/email.service.ts:5:28
backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
backend:start:     3 | import { ConfigService } from '@/common/config';    
backend:start:     4 |
backend:start:   > 5 | import { ConfigType } from 'shared';
backend:start:       |                            ^^^^^^^^
backend:start:     6 |
backend:start:     7 | type IEmailArgs = {
backend:start:     8 |   from: string;
backend:start:
backend:start: ERROR in ./src/libs/payment/payment.service.ts:7:28
backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
backend:start:      5 | import { ConfigService } from '@/common/config';   
backend:start:      6 |
backend:start:   >  7 | import { ConfigType } from 'shared';
backend:start:        |                            ^^^^^^^^
backend:start:      8 |
backend:start:      9 | import { CallbackBody, PaymentArgs, PaymentResponse } from './xunhu';
backend:start:     10 |
backend:start:
backend:start: ERROR in ./src/libs/sms/sms.service.ts:5:28
backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
backend:start:     3 | import { ConfigService } from '@/common/config';    
backend:start:     4 |
backend:start:   > 5 | import { ConfigType } from 'shared';
backend:start:       |                            ^^^^^^^^
backend:start:     6 |
backend:start:     7 | type ISMSArgs = {
backend:start:     8 |   to: string;
backend:start:
backend:start: ERROR in ./src/modules/auth/auth.controller.ts:16:65        
backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
backend:start:     14 | import { WechatService } from '@/modules/auth/wechat.service';
backend:start:     15 |
backend:start:   > 16 | import { forgetPasswordDto, identityDto, validateCodeDto } from 'shared';
backend:start:        |                                                    
             ^^^^^^^^
backend:start:     17 |
backend:start:     18 | import {
backend:start:     19 |   ForgetPasswordSchema,
backend:start:
backend:start: ERROR in ./src/modules/auth/auth.service.ts:16:32
backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
backend:start:     14 | import { ExtendedPrismaClient } from '@/processors/database/prisma.extension';
backend:start:     15 |
backend:start:   > 16 | import { IAccountStatus } from 'shared';
backend:start:        |                                ^^^^^^^^
backend:start:     17 | import { ErrorCodeEnum } from 'shared/dist/error-code';
backend:start:     18 |
backend:start:     19 | type ByPassword = {
backend:start:
backend:start: ERROR in ./src/modules/auth/auth.service.ts:17:31
backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
backend:start:     15 |
backend:start:     16 | import { IAccountStatus } from 'shared';
backend:start:   > 17 | import { ErrorCodeEnum } from 'shared/dist/error-code';
backend:start:        |                               ^^^^^^^^^^^^^^^^^^^^^^^^
backend:start:     18 |
backend:start:     19 | type ByPassword = {
backend:start:     20 |   identity: string;
backend:start:
backend:start: ERROR in ./src/modules/auth/wechat.service.ts:10:28
backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
backend:start:      8 | import { ExtendedPrismaClient } from '@/processors/database/prisma.extension';
backend:start:      9 |
backend:start:   > 10 | import { ConfigType } from 'shared';
backend:start:        |                            ^^^^^^^^
backend:start:     11 |
backend:start:     12 | @Injectable()
backend:start:     13 | export class WechatService {
backend:start:
backend:start: ERROR in ./src/modules/chat/chat.controller.ts:19:31        
backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
backend:start:     17 | import { JWTPayload } from '@/libs/jwt/jwt.service';
backend:start:     18 |
backend:start:   > 19 | import { NewMessageDto } from 'shared';
backend:start:        |                               ^^^^^^^^
backend:start:     20 | import { ErrorCodeEnum } from 'shared/dist/error-code';
backend:start:     21 |
backend:start:     21 | export class ChatService {
backend:start:
backend:start: ERROR in ./src/modules/order/order.controller.ts:21:29
backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
backend:start:     19 | import { PaymentService } from '@/libs/payment/payment.service';
backend:start:     20 |
backend:start:   > 21 | import { newOrderDto } from 'shared';
backend:start:        |                             ^^^^^^^^
backend:start:     22 |
backend:start:     23 | import { OrderService } from './order.service';
backend:start:     24 |
backend:start:
backend:start: webpack 5.89.0 compiled with 17 errors in 3083 ms
backend:start:  ELIFECYCLE  Command failed with exit code 1.
frontend#start: command (D:\ChatGPT-Admin-Web-3\packages\frontend) pnpm run start exited (1)

 Tasks:    0 successful, 2 total
Cached:    0 cached, 2 total
  Time:    4.761s
Failed:    frontend#start

 ERROR  run failed: command  exited (1)
```

**Comment by antiwar3** [comment]
> 遇到了同样的问题 pnpm install 后报依赖错误，db init没问题，start后报错。请问是否是node版本问题？ 环境： win11 node: v20.10.0 docker desktop: Docker version 24.0.7, build afdd53b ![image](https://private-user-images.githubusercontent.com/42081344/288032156-fcd855d0-d6e1-4f1d-b472-b85a7f15a486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTU2MjUsIm5iZiI6MTcwMTkxNTMyNSwicGF0aCI6Ii80MjA4MTM0NC8yODgwMzIxNTYtZmNkODU1ZDAtZDZlMS00ZjFkLWI0NzItYjg1YTdmMTVhNDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAyMTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OGJjZjdiODAxYThlZWYxZTk3ZDhiZTc2OWJhYmE3ZDQ5NmJlZjc1MDgxZTYxMTc4Y2U2M2FhOWJiMjM2ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b-0k-MwvTwG_bVlPjsfdJSKaizbJl8qmxQDDDGUtJts)
> 
> 根目录新建了 `.env`
> 
> ```
> DATABASE_URL=postgres://postgres:mypassword@localhost:5432/postgres
> ```
> 
> 创建容器
> 
> ```
> docker run -itd --name caw -e POSTGRES_PASSWORD=mypassword-p 5432:5432 -d postgres
> ```
> 
> `pnpm run db:init` ![image](https://private-user-images.githubusercontent.com/42081344/288034084-e89da5d2-b508-45c8-91ea-70d64e439385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTU2MjUsIm5iZiI6MTcwMTkxNTMyNSwicGF0aCI6Ii80MjA4MTM0NC8yODgwMzQwODQtZTg5ZGE1ZDItYjUwOC00NWM4LTkxZWEtNzBkNjRlNDM5Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAyMTUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjYjJmY2UzOTQ5YWJjOGNjYzhiMzlmNTVkNmMzZWEzZDE2NmI3MmY5MWM1YzRiN2ZiY2NjNGY4ZmYxNjIzNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wbL23e0zwc8SJLAOTdHOm6mcyc1pkwny8U-Q0KW187o)
> 
> `turbo run start`
> 
> ```
> $ turbo run start
> • Packages in scope: @nest-http/prisma, backend, frontend, shared
> • Running start in 4 packages
> • Remote caching disabled
> backend:start: cache miss, executing bedbf8e6af55f94f
> frontend:start: cache miss, executing eaaef2a6d9402445
> backend:start: 
> backend:start: > backend@ start D:\ChatGPT-Admin-Web-3\packages\backend    
> backend:start: > nest start
> backend:start:
> frontend:start:
> frontend:start: > frontend@ start D:\ChatGPT-Admin-Web-3\packages\frontend 
> frontend:start: > next start
> frontend:start:
> frontend:start: [Error: ENOENT: no such file or directory, open 'D:\ChatGPT-Admin-Web-3\packages\frontend\.next\BUILD_ID'] {
> frontend:start:   errno: -4058,
> frontend:start:   code: 'ENOENT',
> frontend:start:   syscall: 'open',
> frontend:start:   path: 'D:\\ChatGPT-Admin-Web-3\\packages\\frontend\\.next\\BUILD_ID'
> frontend:start: }
> frontend:start:  ELIFECYCLE  Command failed with exit code 1.
> frontend:start: ERROR: command finished with error: command (D:\ChatGPT-Admin-Web-3\packages\frontend) pnpm run start exited (1)
> backend:start: ERROR in ./src/common/config/config.service.ts:8:44
> backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
> backend:start:      6 | import { BizException } from '@/common/exceptions/biz.exception';
> backend:start:      7 |
> backend:start:   >  8 | import { ConfigType, ISettingSchema } from 'shared';
> backend:start:        |                                            ^^^^^^^^
> backend:start:      9 | import { ErrorCodeEnum } from 'shared/dist/error-code';
> backend:start:     10 |
> backend:start:     11 | const DEFAULT_CONFIG = {
> backend:start:
> backend:start: ERROR in ./src/common/config/config.service.ts:9:31
> backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
> backend:start:      7 |
> backend:start:      8 | import { ConfigType, ISettingSchema } from 'shared';
> backend:start:   >  9 | import { ErrorCodeEnum } from 'shared/dist/error-code';
> backend:start:        |                               ^^^^^^^^^^^^^^^^^^^^^^^^
> backend:start:     10 |
> backend:start:     11 | const DEFAULT_CONFIG = {
> backend:start:     12 |   mode: 'nginx',
> backend:start:
> backend:start: ERROR in ./src/common/exceptions/biz.exception.ts:3:31      
> backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
> backend:start:     1 | import { HttpException } from '@nestjs/common';     
> backend:start:     2 |
> backend:start:   > 3 | import { ErrorCodeEnum } from 'shared/dist/error-code';
> backend:start:       |                               ^^^^^^^^^^^^^^^^^^^^^^^^
> backend:start:     4 |
> backend:start:     5 | export const ErrorCode = Object.freeze<
> backend:start:     6 |   Record<ErrorCodeEnum, [string, string, number]>   
> backend:start:
> backend:start: ERROR in ./src/common/filters/all-execption.filter.ts:10:31 
> backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
> backend:start:      8 | } from '@nestjs/common';
> backend:start:      9 |
> backend:start:   > 10 | import { ErrorCodeEnum } from 'shared/dist/error-code';
> backend:start:        |                               ^^^^^^^^^^^^^^^^^^^^^^^^
> backend:start:     11 |
> backend:start:     12 | @Catch()
> backend:start:     13 | export class AllExceptionFilter implements ExceptionFilter {
> backend:start:
> backend:start: ERROR in ./src/common/guards/auth.guard.ts:14:31
> backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
> backend:start:     12 | import { JWTPayload, JwtService } from '@/libs/jwt/jwt.service';
> backend:start:     13 |
> backend:start:   > 14 | import { ErrorCodeEnum } from 'shared/dist/error-code';
> backend:start:        |                               ^^^^^^^^^^^^^^^^^^^^^^^^
> backend:start:     15 |
> backend:start:     16 | export { Role } from '@prisma/client';
> backend:start:     17 | export const ROLES_KEY = 'roles';
> backend:start:
> backend:start: ERROR in ./src/common/pipes/joi.ts:5:31
> backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
> backend:start:     3 | import { BizException } from '@/common/exceptions/biz.exception';
> backend:start:     4 |
> backend:start:   > 5 | import { ErrorCodeEnum } from 'shared/dist/error-code';
> backend:start:       |                               ^^^^^^^^^^^^^^^^^^^^^^^^
> backend:start:     6 |
> backend:start:     7 | @Injectable()
> backend:start:     8 | export class JoiValidationPipe implements PipeTransform {
> backend:start:
> backend:start: ERROR in ./src/libs/email/email.service.ts:5:28
> backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
> backend:start:     3 | import { ConfigService } from '@/common/config';    
> backend:start:     4 |
> backend:start:   > 5 | import { ConfigType } from 'shared';
> backend:start:       |                            ^^^^^^^^
> backend:start:     6 |
> backend:start:     7 | type IEmailArgs = {
> backend:start:     8 |   from: string;
> backend:start:
> backend:start: ERROR in ./src/libs/payment/payment.service.ts:7:28
> backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
> backend:start:      5 | import { ConfigService } from '@/common/config';   
> backend:start:      6 |
> backend:start:   >  7 | import { ConfigType } from 'shared';
> backend:start:        |                            ^^^^^^^^
> backend:start:      8 |
> backend:start:      9 | import { CallbackBody, PaymentArgs, PaymentResponse } from './xunhu';
> backend:start:     10 |
> backend:start:
> backend:start: ERROR in ./src/libs/sms/sms.service.ts:5:28
> backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
> backend:start:     3 | import { ConfigService } from '@/common/config';    
> backend:start:     4 |
> backend:start:   > 5 | import { ConfigType } from 'shared';
> backend:start:       |                            ^^^^^^^^
> backend:start:     6 |
> backend:start:     7 | type ISMSArgs = {
> backend:start:     8 |   to: string;
> backend:start:
> backend:start: ERROR in ./src/modules/auth/auth.controller.ts:16:65        
> backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
> backend:start:     14 | import { WechatService } from '@/modules/auth/wechat.service';
> backend:start:     15 |
> backend:start:   > 16 | import { forgetPasswordDto, identityDto, validateCodeDto } from 'shared';
> backend:start:        |                                                    
>              ^^^^^^^^
> backend:start:     17 |
> backend:start:     18 | import {
> backend:start:     19 |   ForgetPasswordSchema,
> backend:start:
> backend:start: ERROR in ./src/modules/auth/auth.service.ts:16:32
> backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
> backend:start:     14 | import { ExtendedPrismaClient } from '@/processors/database/prisma.extension';
> backend:start:     15 |
> backend:start:   > 16 | import { IAccountStatus } from 'shared';
> backend:start:        |                                ^^^^^^^^
> backend:start:     17 | import { ErrorCodeEnum } from 'shared/dist/error-code';
> backend:start:     18 |
> backend:start:     19 | type ByPassword = {
> backend:start:
> backend:start: ERROR in ./src/modules/auth/auth.service.ts:17:31
> backend:start: TS2307: Cannot find module 'shared/dist/error-code' or its corresponding type declarations.
> backend:start:     15 |
> backend:start:     16 | import { IAccountStatus } from 'shared';
> backend:start:   > 17 | import { ErrorCodeEnum } from 'shared/dist/error-code';
> backend:start:        |                               ^^^^^^^^^^^^^^^^^^^^^^^^
> backend:start:     18 |
> backend:start:     19 | type ByPassword = {
> backend:start:     20 |   identity: string;
> backend:start:
> backend:start: ERROR in ./src/modules/auth/wechat.service.ts:10:28
> backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
> backend:start:      8 | import { ExtendedPrismaClient } from '@/processors/database/prisma.extension';
> backend:start:      9 |
> backend:start:   > 10 | import { ConfigType } from 'shared';
> backend:start:        |                            ^^^^^^^^
> backend:start:     11 |
> backend:start:     12 | @Injectable()
> backend:start:     13 | export class WechatService {
> backend:start:
> backend:start: ERROR in ./src/modules/chat/chat.controller.ts:19:31        
> backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
> backend:start:     17 | import { JWTPayload } from '@/libs/jwt/jwt.service';
> backend:start:     18 |
> backend:start:   > 19 | import { NewMessageDto } from 'shared';
> backend:start:        |                               ^^^^^^^^
> backend:start:     20 | import { ErrorCodeEnum } from 'shared/dist/error-code';
> backend:start:     21 |
> backend:start:     21 | export class ChatService {
> backend:start:
> backend:start: ERROR in ./src/modules/order/order.controller.ts:21:29
> backend:start: TS2307: Cannot find module 'shared' or its corresponding type declarations.
> backend:start:     19 | import { PaymentService } from '@/libs/payment/payment.service';
> backend:start:     20 |
> backend:start:   > 21 | import { newOrderDto } from 'shared';
> backend:start:        |                             ^^^^^^^^
> backend:start:     22 |
> backend:start:     23 | import { OrderService } from './order.service';
> backend:start:     24 |
> backend:start:
> backend:start: webpack 5.89.0 compiled with 17 errors in 3083 ms
> backend:start:  ELIFECYCLE  Command failed with exit code 1.
> frontend#start: command (D:\ChatGPT-Admin-Web-3\packages\frontend) pnpm run start exited (1)
> 
>  Tasks:    0 successful, 2 total
> Cached:    0 cached, 2 total
>   Time:    4.761s
> Failed:    frontend#start
> 
>  ERROR  run failed: command  exited (1)
> ```

相同问题

**Comment by AprilNEA** [comment]
Hello, everybody. I've fixed some issues and posted them in `v3-dev`, which can be switched to with the command `git checkout v3-dev`. Can you help me try `v3-dev` to see if it works?

**Comment by AprilNEA** [comment]
The corresponding document is [v3-dev.caw-docs.pages.dev](https://v3-dev.caw-docs.pages.dev)
https://v3-dev.caw-docs.pages.dev/quickstart

**Comment by antiwar3** [comment]
> The corresponding document is [v3-dev.caw-docs.pages.dev](https://v3-dev.caw-docs.pages.dev) https://v3-dev.caw-docs.pages.dev/quickstart

一切正常了

**Comment by antiwar3** [comment]
> The corresponding document is [v3-dev.caw-docs.pages.dev](https://v3-dev.caw-docs.pages.dev) https://v3-dev.caw-docs.pages.dev/quickstart

配置sms信息登录进去了，payment也配置了，点击升级到高级版，里面是空的

**Comment by ufoozhenghao** [comment]
> > The corresponding document is [v3-dev.caw-docs.pages.dev](https://v3-dev.caw-docs.pages.dev) https://v3-dev.caw-docs.pages.dev/quickstart
> 
> 一切正常了



我这边还是有问题
前面 `pnpm run db:init`正常
创建redis后 `pnpm run start`失败

`.env`
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/42081344/ad0fb172-0d09-42cd-ae1f-597d20f307dd)

`pnpm run start`报错
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/42081344/c845ece2-ad99-4bea-accc-a563a7b886a3)

`docker ps`
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/42081344/b929b099-a14e-4072-9eac-7c54ff3a7838)

不知道哪里有问题？

**Comment by ufoozhenghao** [comment]
win11 启动成功, ubuntu22.04 server启动失败...

**Comment by CaptainTomSparta** [comment]
win11 ，started

**Comment by AprilNEA** [comment]
> > > The corresponding document is [v3-dev.caw-docs.pages.dev](https://v3-dev.caw-docs.pages.dev) [v3-dev.caw-docs.pages.dev/quickstart](https://v3-dev.caw-docs.pages.dev/quickstart)
> > 
> > 
> > 一切正常了
> 
> 我这边还是有问题 前面 `pnpm run db:init`正常 创建redis后 `pnpm run start`失败
> 
> `.env` 
> 不知道哪里有问题？

1. 请根据文档，暴露环境变量而不是`.env`
2. 根据报错，请检查你的网络连接

**Comment by AprilNEA** [comment]
> > The corresponding document is [v3-dev.caw-docs.pages.dev](https://v3-dev.caw-docs.pages.dev) [v3-dev.caw-docs.pages.dev/quickstart](https://v3-dev.caw-docs.pages.dev/quickstart)
> 
> 配置sms信息登录进去了，payment也配置了，点击升级到高级版，里面是空的

需要配置 Product 信息，现在的方法是在数据库中手动配置，预计两天内会开放后台面板配置。

**Comment by antiwar3** [comment]
> > > The corresponding document is [v3-dev.caw-docs.pages.dev](https://v3-dev.caw-docs.pages.dev) [v3-dev.caw-docs.pages.dev/quickstart](https://v3-dev.caw-docs.pages.dev/quickstart)
> > 
> > 
> > 配置sms信息登录进去了，payment也配置了，点击升级到高级版，里面是空的
> 
> 需要配置 Product 信息，现在的方法是在数据库中手动配置，预计两天内会开放后台面板配置。

好的 坐等 tks
