### ISSUE TITLE
turbo run start

### ISSUE THREAD

**Issue by spencerwongfeilong** [AprilNEA/ChatGPT-Admin-Web#174]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/127573355/bfe2700e-317c-4a65-8a5d-fdcab1c4752d)

May i know what should i be doing to start the project?

**Comment by AprilNEA** [comment]
> May i know what should i be doing to start the project?

Hello, you can refer to the latest documentation: https://manual.sku.moe/project/chatgpt-admin-web/quickstart, remember to pull the latest version!
