### ISSUE TITLE
[CAW-11] 部署之后点击购买没有反应

### ISSUE THREAD

**Issue by mfxiaosheng** [AprilNEA/ChatGPT-Admin-Web#18]
已经更新了"PAY_APPID", "PAY_APPSECRET"，部署了chat，点击购买之后没有反应。

<sub>[CAW-11](https://linear.app/renailu/issue/CAW-11/部署之后点击购买没有反应)</sub>

**Comment by AprilNEA** [comment]
> 已经更新了"PAY_APPID", "PAY_APPSECRET"，部署了chat，点击购买之后没有反应。

虎皮椒？

**Comment by mfxiaosheng** [comment]
> > 已经更新了"PAY_APPID", "PAY_APPSECRET"，部分设置了聊天，点击购买之后没有反应。
> 
> 虎皮椒？

是的，按照源码的平台对接的。只部署了chat没有部署dash

**Comment by AprilNEA** [comment]
> > > 已经更新了"PAY_APPID", "PAY_APPSECRET"，部分设置了聊天，点击购买之后没有反应。
> > 
> > 
> > 虎皮椒？
> 
> 是的，按照源码的平台对接的。只部署了chat没有部署dash

👌问题已经定位到了

**Comment by AprilNEA** [comment]
请参考文档重新部署:https://docs.lmo.best/docs/configuration/payment/xunhu
问题已经在 https://github.com/AprilNEA/ChatGPT-Admin-Web/commit/d87a4021968b42ae4acac8405950c7d7db017b31 修复
注意环境变量有所更改
