### ISSUE TITLE
启动项目后请求任意接口报错400

### ISSUE THREAD

**Issue by Fnckerpoi** [AprilNEA/ChatGPT-Admin-Web#184]
根据快速开始文档，已经配置好PGSQL和REDIS
并且数据库已生成数据表。
但是进行初始化管理员时发现接口400验证失败，控制台也没有提供相关日志定位。
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/38403438/0fb642dd-4127-43e7-ab23-17c0b68bb6ea)

**Comment by AprilNEA** [comment]
点击`响应`可查看报错信息

**Comment by Fnckerpoi** [comment]
> 点击`响应`可查看报错信息

[shared_1.ErrorCodeEnum.ValidationError]: [
        'Request data validation error',
        '请求参数错误',
        400,
    ]
    我刚重新拉了最新版代码，重新install update一下试试

**Comment by Fnckerpoi** [comment]
最新V3版本测试后已经有异常
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/38403438/a0a0c700-3a43-42a9-bddc-175f2c004fea)

**Comment by AprilNEA** [comment]
请检查输入参数identity为邮箱或手机号，password需8到20位
https://github.com/AprilNEA/ChatGPT-Admin-Web/blob/c30081d2676e23f6d7568b43415b5e59e08fccf0/packages/shared/src/dto/index.ts#L8-L10

**Comment by Fnckerpoi** [comment]
> 请检查输入参数identity为邮箱或手机号，password需8到20位

![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/38403438/4640655c-04ac-46f9-9b0f-c1010f7b9e36)
成功之后数据库密码为null。
接下来尝试登录账号,如图所示异常
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/38403438/7035d403-f5c1-4bc1-8226-96acc5b39bd0)

**Comment by AprilNEA** [comment]
已修复：https://github.com/AprilNEA/ChatGPT-Admin-Web/commit/65190a11a49cd1fdd838b579e63af27c29ae252e
删除数据库记录后重新初始化

**Comment by Fnckerpoi** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/38403438/524df866-046c-4065-8382-28f0575c3400)
initadmin方法没有设置password字段。
初始化管理员后，不知道登录这里是否要走初始化密码？
因为auth登录页请求password接口

**Comment by AprilNEA** [comment]
> 已修复：[65190a1](https://github.com/AprilNEA/ChatGPT-Admin-Web/commit/65190a11a49cd1fdd838b579e63af27c29ae252e) 删除数据库记录后重新初始化

@Fnckerpoi 拉取最新版重新初始化即可
