### ISSUE TITLE
部分接口疑似有异常

### ISSUE THREAD

**Issue by Fnckerpoi** [AprilNEA/ChatGPT-Admin-Web#186]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/38403438/79a10e0a-86d1-48e3-8f02-c2c1424b0a99)
API：http://localhost:3000/api/chat/sessions/

![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/38403438/54a8ff07-17b3-4402-aff1-7ccf9e3c6c71)
API：http://localhost:3000/api/order （404）

baseURL等配置未找到页面入口

**Comment by AprilNEA** [comment]
#205
