### ISSUE TITLE
error：初始化管理员时Request Data Validation Error

### ISSUE THREAD

**Issue by fenglang918** [AprilNEA/ChatGPT-Admin-Web#189]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/87476215/c236cebe-575f-455b-b5a1-c8dd45f4bffc)

**Comment by CN-Jayden** [comment]
同问，我也是这样

**Comment by CN-Jayden** [comment]
报错：POST：........:3000/api/auth/admin/setup 400 (Bad Request)

**Comment by hhc87** [comment]
我也遇到了类似的情况

**Comment by hhc87** [comment]
@CN-Jayden 看了一下代码解决了，代码里对用户名的验证是电话号码或者邮箱，不能乱写用户名
