### ISSUE TITLE
用gpt-4-all 模型 绘图后 ，当消息记录里 有图片的时候 ，无法通过分享功能 下载图片

### ISSUE THREAD

**Issue by sunreview** [AprilNEA/ChatGPT-Admin-Web#191]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

用gpt-4-all 模型 绘图后 ，当消息记录里 有图片的时候 ，无法通过分享功能 下载图片

**Comment by wqjuser** [comment]
官网本身都不支持分享的对话中含有图片
