### ISSUE TITLE
`crypto.randomUUID` is not a function in Edge browser case Appliction error: a client-side exception...

### ISSUE THREAD

**Issue by lobmoo** [AprilNEA/ChatGPT-Admin-Web#193]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/45560941/3eb4d98e-0ebd-49c5-b01f-ff1e0242c3a2)
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/45560941/769c832b-e49e-4aeb-8817-fba897d037d6)

**Comment by AprilNEA** [comment]
根据 https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
非 https 的话建议用 Google Chrome，Edge 在非 https 下不支持`randomUUID`

稍后会在文档中添加说明并考虑添加后备方案。

Based on https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

Google Chrome is recommended for non-https, Edge does not support `randomUUID` for non-https.

Will add a note to the docs later and consider adding a fallback.

**Comment by AprilNEA** [comment]
Reopen until you a note to the document and consider adding a fallback option.

**Comment by lobmoo** [comment]
能冒昧问下，怎么配置成https吗？目前好像编译完之后就是hppt

**Comment by lobmoo** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/45560941/16c61be2-2300-469b-bdd2-c745ac69677c)
这样改了一下貌似可以了

**Comment by AprilNEA** [comment]
Fixed in `v3.2.4`
