### ISSUE TITLE
pnpm run start 报错

### ISSUE THREAD

**Issue by jqjhl** [AprilNEA/ChatGPT-Admin-Web#194]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/96766882/f15585e1-46db-4f35-a922-7600d7ec68f5)
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/96766882/65e02e89-208c-4fd5-86d7-4c2dc5c3b5dc)

**Comment by AprilNEA** [comment]
请检查 Node.js. 版本以及依赖是否正确安装。
