### ISSUE TITLE
是不是后台的接口缺少，如图无法调用到接口样的

### ISSUE THREAD

**Issue by deluxebear** [AprilNEA/ChatGPT-Admin-Web#195]
![企业微信截图_17031537991125](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/485793/90eaff5d-7a1c-4c27-ab36-590dd602c925)

**Comment by haimianbaobao111** [comment]
同样的问题，我也遇到了

**Comment by Pandolar** [comment]
我也遇到了相似的问题 
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/54896726/22b0c06a-d725-4785-86e1-258fc0b0b03c)
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/54896726/f0185382-0463-4a97-b281-33d9c25d09ea)
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/54896726/543b7c0f-dc0e-4584-9dd1-14aea7f3ae72)

**Comment by AprilNEA** [comment]
邮箱或手机号

**Comment by AprilNEA** [comment]
已修改placeholder：[8498391](https://github.com/AprilNEA/ChatGPT-Admin-Web/commit/8498391d507f81f9f3a3b68e945816eac66e9ee6)

**Comment by 1670313770** [comment]
> 我也遇到了相似的问题 ![image](https://private-user-images.githubusercontent.com/54896726/292812420-22b0c06a-d725-4785-86e1-258fc0b0b03c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDQwMjcsIm5iZiI6MTcwNDAwMzcyNywicGF0aCI6Ii81NDg5NjcyNi8yOTI4MTI0MjAtMjJiMGMwNmEtZDcyNS00Nzg1LTg2ZTEtMjU4ZmMwYjBiMDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA2MjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMDAyMzI3YjhkYjJiNDMzMGExZmJmMDg2ZGMwMmQ1MTZhOWU0NWI0ZTAwNTZmMzM2OGNjZWEzMWViZjE0MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uSzASAbJw_uzP6VjRBAC_kFLKQgDDuCIw6mfXSFWD00) ![image](https://private-user-images.githubusercontent.com/54896726/292812510-f0185382-0463-4a97-b281-33d9c25d09ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDQwMjcsIm5iZiI6MTcwNDAwMzcyNywicGF0aCI6Ii81NDg5NjcyNi8yOTI4MTI1MTAtZjAxODUzODItMDQ2My00YTk3LWIyODEtMzNkOWMyNWQwOWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA2MjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YjJiN2JkZTE2ZTg1MTcyYTNmNDlhYmE5MGFlYzU0NDY1MjVkMWNjYTQzMWFmYzgyNTE2YTUyZmIxMTYxMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0DyVUO6FHxHwM0XAQhfZI_h1wHoXoRBlSsaLeEO7Sa4) ![image](https://private-user-images.githubusercontent.com/54896726/292812540-543b7c0f-dc0e-4584-9dd1-14aea7f3ae72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDQwMjcsIm5iZiI6MTcwNDAwMzcyNywicGF0aCI6Ii81NDg5NjcyNi8yOTI4MTI1NDAtNTQzYjdjMGYtZGMwZS00NTg0LTlkZDEtMTRhZWE3ZjNhZTcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA2MjIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZGI0OTdjMTFiZjVmODU2ZTQ0YTlhYzc1MDllZTJhODNkNmY5ZjAzYzEzYTEzNWY4YWQwNzI5MjU0MDMyZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RcyAJ_azJ9fLSaiNtHU7GFHtUQkKyibeFaByjluuv3g)

我也是这样
