### ISSUE TITLE
http://localhost:3000/install 写入不了

### ISSUE THREAD

**Issue by yahengqi** [AprilNEA/ChatGPT-Admin-Web#196]
https://manual.sku.moe/project/chatgpt-admin-web/quickstart
安装这个上面一步一步，在本地搭建好了，本地安装的docker，redis，postgres
1.http://localhost:3000/install 创建不了管理员
2.http://localhost:3000/auth 也无法登陆
请问下是否需要搭建数据库，在哪个文件里修改呢

**Comment by Guikong001** [comment]
我也是，数据库是用docker新建的
创建初始用户的时候显示
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/101174061/1a93c2d0-ffe1-4860-8885-bebbf442146b)

**Comment by deluxebear** [comment]
好像都有这问题，不知道作者有没有看到消息，帮忙处理一下呗

**Comment by assassinliujie** [comment]
同样的问题

**Comment by assassinliujie** [comment]
手动访问数据库之后好了，怀疑就那个创建管理员函数出bug了

**Comment by yahengqi** [comment]
> 手动访问数据库之后好了，怀疑就那个创建管理员函数出bug了
问下如何手动访问数据库，在哪个文件里

**Comment by assassinliujie** [comment]
> > 手动访问数据库之后好了，怀疑就那个创建管理员函数出bug了
> > 问下如何手动访问数据库，在哪个文件里
就是PostgreSQL啊，你随便用个习惯的工具连进去自己填上一行数据就好了，密码是用10强度的bcrypt加密的，找个在线生成的

**Comment by yahengqi** [comment]
> > > 手动访问数据库之后好了，怀疑就那个创建管理员函数出bug了
> > > 问下如何手动访问数据库，在哪个文件里
> > > 就是PostgreSQL啊，你随便用个习惯的工具连进去自己填上一行数据就好了，密码是用10强度的bcrypt加密的，找个在线生成的

好吧，相当于库中至少有一条数据，谢谢

**Comment by AprilNEA** [comment]
> 我也是，数据库是用docker新建的 创建初始用户的时候显示 ![image](https://private-user-images.githubusercontent.com/101174061/292630682-1a93c2d0-ffe1-4860-8885-bebbf442146b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NDQzNzUsIm5iZiI6MTcwMzY0NDA3NSwicGF0aCI6Ii8xMDExNzQwNjEvMjkyNjMwNjgyLTFhOTNjMmQwLWZmZTEtNDg2MC04ODg1LWJlYmJmNDQyMTQ2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QwMjI3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGQ0YWFhMzQ4OTFiNDI5M2YyYTI1ZGVjYWZhZjA5Yzg0NDIzNzdjMWJlMjRmNzIwOTUxMTk5M2U1NjU2ODU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S_G15jV1mGm6Tbt5LfS_rbCdlmU6zJ2QaghSiPX93kQ)

邮箱或手机号

**Comment by AprilNEA** [comment]
已修改placeholder：[8498391](https://github.com/AprilNEA/ChatGPT-Admin-Web/commit/8498391d507f81f9f3a3b68e945816eac66e9ee6)
