### ISSUE TITLE
项目目前是正在开发状态吗？

### ISSUE THREAD

**Issue by assassinliujie** [AprilNEA/ChatGPT-Admin-Web#197]
添加管理员功能用不了，手动进数据库添加之后绕过了，然后进去之后许多按钮点了没有效果

**Comment by AprilNEA** [comment]
邮箱或手机号

**Comment by AprilNEA** [comment]
已修改placeholder：[8498391](https://github.com/AprilNEA/ChatGPT-Admin-Web/commit/8498391d507f81f9f3a3b68e945816eac66e9ee6)
