### ISSUE TITLE
pnpm run start ERROR

### ISSUE THREAD

**Issue by 0smboy** [AprilNEA/ChatGPT-Admin-Web#199]
pnpm run start

> chatgpt-admin-web@3.2.4 start /workspaces/ChatGPT-Admin-Web
> turbo run start

• Packages in scope: @nest-http/prisma, backend, frontend, shared
• Running start in 4 packages
• Remote caching disabled
frontend:start: cache miss, executing a51b00639a0dfe13
backend:start: cache miss, executing be1da5ec7d1208d5
frontend:start: 
frontend:start: > frontend@ start /workspaces/ChatGPT-Admin-Web/packages/frontend
frontend:start: > next start
frontend:start: 
backend:start: 
backend:start: > backend@ start /workspaces/ChatGPT-Admin-Web/packages/backend
backend:start: > nest start
backend:start: 
frontend:start:  ⚠ Invalid next.config.js options detected: 
frontend:start:  ⚠     "env.LOGO" is missing, expected string
frontend:start:  ⚠     "env.LOGO_BOT" is missing, expected string
frontend:start:  ⚠     "env.LOGO_LOGIN" is missing, expected string
frontend:start:  ⚠     "env.LOGO_LOADING" is missing, expected string
frontend:start:  ⚠     "env.LOGO_SIDEBAR" is missing, expected string
frontend:start:  ⚠     "env.ONBOARDING" is missing, expected string
frontend:start:  ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
frontend:start: [Error: ENOENT: no such file or directory, open '/workspaces/ChatGPT-Admin-Web/packages/frontend/.next/BUILD_ID'] {
frontend:start:   errno: -2,
frontend:start:   code: 'ENOENT',
frontend:start:   syscall: 'open',
frontend:start:   path: '/workspaces/ChatGPT-Admin-Web/packages/frontend/.next/BUILD_ID'
frontend:start: }
frontend:start:  ELIFECYCLE  Command failed with exit code 1.
frontend:start: ERROR: command finished with error: command (/workspaces/ChatGPT-Admin-Web/packages/frontend) pnpm run start exited (1)
frontend#start: command (/workspaces/ChatGPT-Admin-Web/packages/frontend) pnpm run start exited (1)

 Tasks:    0 successful, 2 total
Cached:    0 cached, 2 total
  Time:    982ms 
Failed:    frontend#start

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
/workspaces/ChatGPT-Admin-Web (v3) $ find ./ -name "config.json"
/workspaces/ChatGPT-Admin-Web (v3) $

**Comment by AprilNEA** [comment]
You should build it first
