### ISSUE TITLE
maigun免费账号发不了邮件？

### ISSUE THREAD

**Issue by ludashi2020** [AprilNEA/ChatGPT-Admin-Web#20]
Domain sandbox6b44e890a60d4618b9f134cfdc587002.mailgun.org is not allowed to send: Sandbox subdomains are for test purposes only. Please add your own domain or add the address to authorized recipients in Account Settings.

能否支持腾讯邮箱或者阿里邮箱呢？

**Comment by AprilNEA** [comment]
免费账户不是很清楚，如果能确定的话麻烦再给一下反馈。
腾讯云邮箱会提供支持。

**Comment by ludashi2020** [comment]
maigun账户已经升级。使用命令行方式可以正常发邮件了，但是网页版发送不了邮件，报错了。链接报错：
![WeChat截图_20230505201553.png](https://pic.shenbian.tv/2023/05/05/af90a5e4aae28.png)

**Comment by AprilNEA** [comment]
已在https://github.com/AprilNEA/ChatGPT-Admin-Web/commit/1ac5ed4ff6d2914d3ec678c06cac7b4920ed591f中修复，需要同步上游并重新部署，重新部署之前修改一下环境变量的名称。
环境变量的名称稍微有些变动，为了后面拓展其他邮件服务器。
`MAIL_API_KEY`->`MAILGUN_API_KEY`
文档：https://docs.lmo.best/docs/configuration/email
