### ISSUE TITLE
任何请求都报500错

### ISSUE THREAD

**Issue by 1670313770** [AprilNEA/ChatGPT-Admin-Web#200]
![截图_20231231142014](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/47101180/e9368844-5187-47d0-b82d-76111270c3fc)

**Comment by AprilNEA** [comment]
请给出更多环境信息

**Comment by 1670313770** [comment]
> 请给出更多环境信息

![截图_20231231182314](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/47101180/882e6be3-92ff-43f4-acf2-234a3ddbfc66)
![截图_20231231182400](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/47101180/0461902f-444b-40ab-ba96-586c4a301c4a)
![截图_20231231182538](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/47101180/8e72455c-f31f-4d50-bad0-54a8ddf62450)
http://106.75.250.46:3000/auth
所有接口的报错都是
500
{
  "success": false,
  "code": 99999,
  "message": "Headers is not defined"
}

**Comment by 1670313770** [comment]
> 请给出更多环境信息

问题找到了，是node版本问题，我重新编译后可以了
