### ISSUE TITLE
请设置环境变量 DATABASE_URL 和 REDIS_URLPlease set the environment variables DATABASE_URL and REDIS_URL.

### ISSUE THREAD

**Issue by yahengqi** [AprilNEA/ChatGPT-Admin-Web#201]
在根目录创建.env或者config.json,把这两个路径写进去
sudo pnpm run start 一直报
请设置环境变量 DATABASE_URL 和 REDIS_URLPlease set the environment variables DATABASE_URL and REDIS_URL.
<img width="879" alt="截屏2023-12-31 16 38 27" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/40587285/2ce465e4-ff89-4bc3-9762-d5defd42421e">

**Comment by AprilNEA** [comment]
首次启动：删除`config.json`并确保`.env`格式无误。

**Comment by yahengqi** [comment]
执行 sudo pnpm run start 
之后提示请设置环境变量
http://localhost:3000/install
填写手机号和密码之后

<img width="1320" alt="截屏2023-12-31 18 24 54" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/40587285/3063c89a-c35e-4987-b43f-c02aebd631e6">

您好，看下.env设置的对不对
<img width="801" alt="截屏2023-12-31 18 25 26" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/40587285/5be4b6f0-36aa-44be-a3f6-4f3056b2202d">

**Comment by AprilNEA** [comment]
`.env`应当在根目录
