### ISSUE TITLE
resend邮件服务无法访问？

### ISSUE THREAD

**Issue by 0smboy** [AprilNEA/ChatGPT-Admin-Web#202]
![telegram-cloud-photo-size-5-6093490396459022558-y](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/91452062/e243adde-c3dd-4a30-803f-05f75e9da68c)
![telegram-cloud-photo-size-5-6093490396459022557-y](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/91452062/eba260ec-6006-4fb3-9565-d3abed2c8a4d)
我在resend官方发邮件是正常的，部署在本地使用相同的配置发邮件报500错误
是否需要配置邮件代理？

**Comment by AprilNEA** [comment]
如果服务器架设在国内，可能需要代理。
