### ISSUE TITLE
启动项目pnpm run start报错

### ISSUE THREAD

**Issue by kaine380** [AprilNEA/ChatGPT-Admin-Web#204]
(base) kaine380@192 ChatGPT-Admin-Web % pnpm run start

> chatgpt-admin-web@3.2.4 start /Users/kaine380/ChatGPT-Admin-Web
> turbo run start

• Packages in scope: @nest-http/prisma, backend, frontend, shared
• Running start in 4 packages
• Remote caching disabled
frontend:start: cache miss, executing 8e5f0c252034495a
backend:start: cache miss, executing fbc215eec577a971
frontend:start: 
frontend:start: > frontend@ start /Users/kaine380/ChatGPT-Admin-Web/packages/frontend
frontend:start: > next start
frontend:start: 
backend:start: 
backend:start: > backend@ start /Users/kaine380/ChatGPT-Admin-Web/packages/backend
backend:start: > nest start
backend:start: 
frontend:start:  ⚠ Invalid next.config.js options detected: 
frontend:start:  ⚠     "env.LOGO" is missing, expected string
frontend:start:  ⚠     "env.LOGO_BOT" is missing, expected string
frontend:start:  ⚠     "env.LOGO_LOGIN" is missing, expected string
frontend:start:  ⚠     "env.LOGO_LOADING" is missing, expected string
frontend:start:  ⚠     "env.LOGO_SIDEBAR" is missing, expected string
frontend:start:  ⚠     "env.ONBOARDING" is missing, expected string
frontend:start:  ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
frontend:start: [Error: ENOENT: no such file or directory, open '/Users/kaine380/ChatGPT-Admin-Web/packages/frontend/.next/BUILD_ID'] {
frontend:start:   errno: -2,
frontend:start:   code: 'ENOENT',
frontend:start:   syscall: 'open',
frontend:start:   path: '/Users/kaine380/ChatGPT-Admin-Web/packages/frontend/.next/BUILD_ID'
frontend:start: }
frontend:start:  ELIFECYCLE  Command failed with exit code 1.
frontend:start: ERROR: command finished with error: command (/Users/kaine380/ChatGPT-Admin-Web/packages/frontend) /usr/local/bin/pnpm run start exited (1)
backend:start:  ELIFECYCLE  Command failed.
frontend#start: command (/Users/kaine380/ChatGPT-Admin-Web/packages/frontend) /usr/local/bin/pnpm run start exited (1)

 Tasks:    0 successful, 2 total
Cached:    0 cached, 2 total
  Time:    890ms 
Failed:    frontend#start

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by Chenkeyi43** [comment]
同问，项目不维护了吗？

**Comment by AprilNEA** [comment]
请先`pnpm run build`
