### ISSUE TITLE
 Failed to proxy http://localhost:3001/api/auth/password Error: connect ECONNREFUSED ::1:3001

### ISSUE THREAD

**Issue by EROMANGAG** [AprilNEA/ChatGPT-Admin-Web#206]
![图片](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/61773351/ac0b37ab-003a-4c80-9818-59f293131f37)

**Comment by EROMANGAG** [comment]
3001是后端的端口吗？似乎无法访问

**Comment by AprilNEA** [comment]
<img width="889" alt="image" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/37977109/738e12cf-ebb3-4b09-8a19-09796116e484">

**Comment by EROMANGAG** [comment]
> <img alt="image" width="889" src="https://private-user-images.githubusercontent.com/37977109/295799015-738e12cf-ebb3-4b09-8a19-09796116e484.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTIzMzUsIm5iZiI6MTcwNDk1MjAzNSwicGF0aCI6Ii8zNzk3NzEwOS8yOTU3OTkwMTUtNzM4ZTEyY2YtZWJiMy00YjA5LThhMTktMDk3OTYxMTZlNDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA1NDcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZTNhZWJjZGE0OGEyN2M4NzRmY2Y0N2VkOWYwNDRlMWY0Y2NmMTQxZGExNjU5Njg4MjBlNDQzYTZjNDlhNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LhAntws81rYisAedH5s7zgGJPAWpqboTSKtGWsgXZbE">

请问如何设置环境变量？
