### ISSUE TITLE
验证码无法发送

### ISSUE THREAD

**Issue by Chenm4** [AprilNEA/ChatGPT-Admin-Web#22]
![image](https://user-images.githubusercontent.com/98648589/236589284-88d037fb-241c-43a1-b604-77c8cf218e3f.png)
![image](https://user-images.githubusercontent.com/98648589/236589307-7c5e7593-0d1a-4679-950e-006b80e6a1cf.png)
![image](https://user-images.githubusercontent.com/98648589/236589331-63db2a34-a4f5-4e33-bff4-09c31fb9cf23.png)
![image](https://user-images.githubusercontent.com/98648589/236589517-03f17319-3012-40f1-aa6a-05a735dde519.png)
![image](https://user-images.githubusercontent.com/98648589/236589658-56e90755-d445-4a4a-a29b-58e7b8f93461.png)
请问一下这是什么原因？环境变量和控制台报错均在上面截图中，我这边没有收到任何验证码

**Comment by Chenm4** [comment]
拉取了最新commit后发现还是不行，不过发送完验证码会提示已成功发送，但实际上我邮箱没有收到验证码

**Comment by ludashi2020** [comment]
你不是一个人

**Comment by ludashi2020** [comment]
对了，你的邮箱域名不能使用默认赠送的域名，那个无法发送邮件的。自己添加一个自己的域名上去。

**Comment by Chenm4** [comment]
> 对了，你的邮箱域名不能使用默认赠送的域名，那个无法发送邮件的。自己添加一个自己的域名上去。

噢噢，好的，感谢

**Comment by AprilNEA** [comment]
1. 最新版环境变量名称有更改，请参考最新的文档。
2. Mailgun 免费版无法发送邮件，可以使用 Elastice
