### ISSUE TITLE
希望完善后台的部署文档

### ISSUE THREAD

**Issue by mfxiaosheng** [AprilNEA/ChatGPT-Admin-Web#23]
当我点击购买时没有任何反应，我猜测是因为从数据库读取价格的时候没有读取到，而这块的设置应该是在后台里面。

**Comment by ludashi2020** [comment]
后台部署了，但是如何设置管理员呢？

**Comment by mfxiaosheng** [comment]
> 后台部配备了，但是如何设置管理人员呢？

如何部署后台? 管理员是读的数据库，所以理论上可以直接修改数据库的字段把你的账号权限升级为管理员

**Comment by ludashi2020** [comment]
upstash免费版无法直接修改数据库字段

**Comment by mfxiaosheng** [comment]
通过代码直接写入数据库就可以了

**Comment by ludashi2020** [comment]
后台进去了，是这样的。没啥功能啊。![WeChat截图_20230506145139.png](https://pic.shenbian.tv/2023/05/06/526fa5cf2107c.png)
