### ISSUE TITLE
使用ELASTICE仍然不能接收到验证码

### ISSUE THREAD

**Issue by Chenm4** [AprilNEA/ChatGPT-Admin-Web#24]
下图为vercel部署的环境变量![image](https://user-images.githubusercontent.com/98648589/236598356-ff97fb7c-6722-4ff1-865d-af0ee198868c.png)
其中key是在下图位置中生成的key
![image](https://user-images.githubusercontent.com/98648589/236598392-414e1849-278d-4b1c-b37b-f9862e044145.png)
也设置模板了
![image](https://user-images.githubusercontent.com/98648589/236598423-3cb73e81-060d-4cb4-acdf-a6cbd534aad2.png)
设置的邮箱
![_QXR_2WHW}GIR7K@PQFZUNI](https://user-images.githubusercontent.com/98648589/236598454-d067790b-668a-46ad-bcba-d215cd99d02b.png)
不知道哪个环节出错了，vercel重新部署完还是接收不到验证码，希望有大佬能解惑，谢谢谢谢

**Comment by Chenm4** [comment]
本项目代码中的返回值response代表了通过HTTP请求发送邮件的服务器返回的响应结果，而不是邮箱服务器返回的邮件发送状态码。希望能改成后者，因为前者返回成功但是可能实际上并未成功发送

**Comment by Wannabeasmartguy** [comment]
我也一样。
另外在尝试mailgun时，打开mailgun发送的激活邮件，填入手机激活账号时必然出现**“An error occurred while attempting to send your verification code. This phone number could already be associated with another account, or there may be too many active verification codes. Please Contact Support if the issue persists”**.这个发送验证码过于频繁的错误，无论是用接码平台的号还是自己号都无济于事。
蹲一个大佬

**Comment by AprilNEA** [comment]
@Chenm4 
![image](https://user-images.githubusercontent.com/37977109/236659547-30d81ae6-3d1f-425a-8c43-28599d05fb41.png)

这个权限给了吗

**Comment by AprilNEA** [comment]
> 我也一样。 另外在尝试mailgun时，打开mailgun发送的激活邮件，填入手机激活账号时必然出现**An error occurred while attempting to send your verification code. This phone number could already be associated with another account, or there may be too many active verification codes. Please Contact Support if the issue persists**

请尝试与 mailgun 的支持取得联系

**Comment by zhuangjia777** [comment]
mailgun测试邮件发送成功，但web应用点击get code，提示“请确保邮箱，密码和验证码输入完整”，mailgun的Log里也没有显示

**Comment by Chenm4** [comment]
> @Chenm4 ![image](https://user-images.githubusercontent.com/37977109/236659547-30d81ae6-3d1f-425a-8c43-28599d05fb41.png)
> 
> 这个权限给了吗

感谢，是这个问题

**Comment by AprilNEA** [comment]
> mailgun测试邮件发送成功，但web应用点击get code，提示“请确保邮箱，密码和验证码输入完整”，mailgun的Log里也没有显示

你没输入邮箱吧

**Comment by zhuangjia777** [comment]
![firefox_1ntqTABcHw](https://user-images.githubusercontent.com/107106464/236841074-1b64a676-3f35-4f76-8b9c-b73672206fe4.png)

**Comment by zhuangjia777** [comment]
![firefox_bGk3VlnLe0](https://user-images.githubusercontent.com/107106464/236841170-73973758-a8b0-4219-9289-4b3c316599b6.png)

**Comment by lyhh123** [comment]
同样配置了所有环境变量，测试邮件也发送成功了，但是就是注册不给发邮件

**Comment by xujinjie666** [comment]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/109212789/23463993-66eb-42dc-a21f-1a6f06b04e50)
获取验证码报500是什么原因啊

**Comment by Xiaoxinkeji** [comment]
> ![图像](https://user-images.githubusercontent.com/109212789/239683156-23463993-66eb-42dc-a21f-1a6f06b04e50.png)获取验证码报500是什么原因啊
一样，我也遇到这个问题了
