### ISSUE TITLE
【newbing error】but gpt-3.5-turbo is ok

### ISSUE THREAD

**Issue by sumerzhang** [AprilNEA/ChatGPT-Admin-Web#26]
when I using gpt-3.5-turbo model  is right, but when change it to newbing model, I got this error 
```shell
{"issues":[{"received":"newbing","code":"invalid_enum_value","options":["gpt-3.5-turbo","gpt-4"],"path":["model"],"message":"Invalid enum value. Expected 'gpt-3.5-turbo' | 'gpt-4', received 'newbing'"}],"name":"ZodError"}
```

My .env config file is like this 

<img width="955" alt="16833565122255" src="https://user-images.githubusercontent.com/37577949/236608780-8b7d04f2-737c-42c4-b48c-9a94e751de81.png">

**Comment by sumerzhang** [comment]
this is solved.
BING_COOKIE should be like this, 
<img width="897" alt="20230506182259" src="https://user-images.githubusercontent.com/37577949/236618586-c7563a34-213e-4108-8efa-4dc4107d9025.png">

call bing success

<img width="813" alt="20230506182429" src="https://user-images.githubusercontent.com/37577949/236618606-f640a819-6ede-44c5-b14f-3815dc5cd54d.png">

Some other stuff was also modified by me, but I have no detailed record of them.

I would like to hear about your errors and trials.

**Comment by AprilNEA** [comment]
> I would like to hear about your errors and trials.

We fixed an early type error related to zod. Currently, it is not experienced in this repository. We will fix it soon. 

This is the reason why Bing cannot be used.
