### ISSUE TITLE
[Feature] JAVA 版 愿意奉献JAVA后台管理实现

### ISSUE THREAD

**Issue by jonsey888** [AprilNEA/ChatGPT-Admin-Web#29]

**Comment by PeronGH** [comment]
你好，

本项目目前 dash 的后端和 chat 的后端共用了数据库相关代码，多一个 Java 版本不利于代码复用和同步。而且多一个 Java 版本也不利于部署至 Vercel。

感谢您的建议，期待您对本项目的持续关注和支持。
