### ISSUE TITLE
vercel 部署报错 No Output Directory named "public" found after the Build completed.

### ISSUE THREAD

**Issue by zyxyxz** [AprilNEA/ChatGPT-Admin-Web#3]
<html>
<body>

...writing to cache...
--
17:30:04.205 | Error: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.
17:30:04.206 | Learn More: https://vercel.link/missing-public-directory
17:30:04.818 | Deployment completed
17:30:04.430 | STATIC_BUILD_NO_OUT_DIR: No Output Directory named "public" found after the Build completed. You can configure the Output Directory in your Project Settings.

</body>
</html>

![image](https://user-images.githubusercontent.com/31527923/235631847-170cea37-262a-4dbd-8891-89b22614d42a.png)

**Comment by seshubonam** [comment]
+1 , yeah same problem. thanks
