### ISSUE TITLE
[CAW-15] [Feature] 添加易支付和支付宝当面付

### ISSUE THREAD

**Issue by black-fruit** [AprilNEA/ChatGPT-Admin-Web#32]
对个人站长有很大帮助哦

<sub>[CAW-15](https://linear.app/renailu/issue/CAW-15/[feature]-添加易支付和支付宝当面付)</sub>

**Comment by AprilNEA** [comment]
能否给出相关的文档链接

**Comment by black-fruit** [comment]
当面付是支付宝官方的，易支付没有文档，另外问一下默认密码是什么

**Comment by black-fruit** [comment]
这个东西用起来也有点一头雾水

**Comment by black-fruit** [comment]
另外有些没完善的文档我可以写

**Comment by AprilNEA** [comment]
> 另外有些没完善的文档我可以写

提 PR 即可

**Comment by despacito008** [comment]
> 能否给出相关的文档链接

https://pay.v8jisu.cn/doc.html
易支付的相关文档

**Comment by black-fruit** [comment]
> > 能否给出相关的文档链接
> 
> https://pay.v8jisu.cn/doc.html
> 易支付的相关文档

一看就是来打广子的

**Comment by despacito008** [comment]
> > > 能否给出相关的文档链接
> > 
> > 
> > https://pay.v8jisu.cn/doc.html
> > 易支付的相关文档
> 
> 一看就是来打广子的

闭上你的臭嘴，这是易支付正版官网的演示网站

**Comment by black-fruit** [comment]
> > > > 能否给出相关的文档链接
> > > 
> > > 
> > > https://pay.v8jisu.cn/doc.html
> > > 易支付的相关文档
> > 
> > 
> > 一看就是来打广子的
> 
> 闭上你的臭嘴，这是易支付正版官网的演示网站

易支付，哪套系统

**Comment by AprilNEA** [comment]
#135 Progress tracking by #135.
