### ISSUE TITLE
[CAW-19] [Feature] 添加微信登录

### ISSUE THREAD

**Issue by Oh-Little-Papaya** [AprilNEA/ChatGPT-Admin-Web#36]
可以考虑使用微信登录吗？或者补上手机号注册也可以。

<sub>[CAW-19](https://linear.app/renailu/issue/CAW-19/可以考虑使用微信登录吗？或者补上手机号注册也可以。)</sub>

**Comment by AprilNEA** [comment]
这个优先级会比较高

**Comment by zlazlazl** [comment]
> * [ ]  接入微信公众号登录
> * [ ]  短信登录

短信可以支持阿里云短信吗

**Comment by AprilNEA** [comment]
![Uploading cover2.png…]()
