### ISSUE TITLE
[FAQ] 添加使用限制次数

### ISSUE THREAD

**Issue by tomridder** [AprilNEA/ChatGPT-Admin-Web#37]
代码如图所示
是不是plan:要设置成free才行
![643381D4-41C6-43AC-A572-8DCEBE24BCCE](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/13205117/5ebdf104-07a8-4931-ba79-99aea98de9df)

**Comment by AprilNEA** [comment]
>是不是plan:要设置成free才行

对，因为你的用户账户是free

**Comment by tomridder** [comment]
set plan:free "{\"limits\": {\"gpt-4\": { \"limit\": 50, \"window\": \"1d\" }, \"gpt-3.5-turbo\": { \"limit\": 3000000000, \"window\": \"88h\" } }, \"prices\": {\"monthly\": 0, \"quarterly\": 0, \"yearly\": 0}}"
再询问下楼主 我这样设置，按理说limit300万次，windows是88h。但是只要设置了plan:free就无法回答了，一次都不行，del plan:free 后立马就可以了。
问下是哪个语法或者变量错了

**Comment by tomridder** [comment]
命令语法错误

**Comment by tanzhiquan** [comment]
> set plan:free "{"limits": {"gpt-4": { "limit": 50, "window": "1d" }, "gpt-3.5-turbo": { "limit": 3000000000, "window": "88h" } }, "prices": {"monthly": 0, "quarterly": 0, "yearly": 0}}" 再询问下楼主 我这样设置，按理说limit300万次，windows是88h。但是只要设置了plan:free就无法回答了，一次都不行，del plan:free 后立马就可以了。 问下是哪个语法或者变量错了

我也遇到你这个问题了，可以贴一下，正确的配置json吗？

**Comment by macshion** [comment]
> "{"limits": {"gpt-4": { "limit": 50, "window": "1d" }, "gpt-3.5-turbo": { "limit": 3000000000, "window": "88h" } }, "prices": {"monthly": 0, "quarterly": 0, "yearly": 0}}"

`JSON.SET plan:free $ '{"limits": {"gpt-4": { "limit": 50, "window": "1m" }, "gpt-3.5-turbo": { "limit": 3000, "window": "1m" } }, "prices": {"monthly": 0, "quarterly": 0, "yearly": 0}}'`

**Comment by macshion** [comment]
> > set plan:free "{"limits": {"gpt-4": { "limit": 50, "window": "1d" }, "gpt-3.5-turbo": { "limit": 3000000000, "window": "88h" } }, "prices": {"monthly": 0, "quarterly": 0, "yearly": 0}}" 再询问下楼主 我这样设置，按理说limit300万次，windows是88h。但是只要设置了plan:free就无法回答了，一次都不行，del plan:free 后立马就可以了。 问下是哪个语法或者变量错了
> 
> 我也遇到你这个问题了，可以贴一下，正确的配置json吗？

```
JSON.SET plan:free $ '{"limits": {"gpt-4": { "limit": 50, "window": "1m" }, "gpt-3.5-turbo": { "limit": 3000, "window": "1m" } }, "prices": {"monthly": 0, "quarterly": 0, "yearly": 0}}'
```

**Comment by macshion** [comment]
> > > set plan:free "{"limits": {"gpt-4": { "limit": 50, "window": "1d" }, "gpt-3.5-turbo": { "limit": 3000000000, "window": "88h" } }, "prices": {"monthly": 0, "quarterly": 0, "yearly": 0}}" 再询问下楼主 我这样设置，按理说limit300万次，windows是88h。但是只要设置了plan:free就无法回答了，一次都不行，del plan:free 后立马就可以了。 问下是哪个语法或者变量错了
> > 
> > 
> > 我也遇到你这个问题了，可以贴一下，正确的配置json吗？
> 
> ```
> JSON.SET plan:free $ '{"limits": {"gpt-4": { "limit": 50, "window": "1m" }, "gpt-3.5-turbo": { "limit": 3000, "window": "1m" } }, "prices": {"monthly": 0, "quarterly": 0, "yearly": 0}}'
> ```

费了好大的劲，xiao'ku😂
<img width="1053" alt="image" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/31300385/a860f997-b3a0-4601-b303-762bdc80e430">
