### ISSUE TITLE
[CAW-20] [Feature] 云端同步消息存储

### ISSUE THREAD

**Issue by baby2431** [AprilNEA/ChatGPT-Admin-Web#38]
请求是否加入消息的数据库存储功能

<sub>[CAW-20](https://linear.app/renailu/issue/CAW-20/[feature]-云端同步消息存储)</sub>

**Comment by AprilNEA** [comment]
计划中

**Comment by VectorZhao** [comment]
支持，云端存储消息确实方便，手机电脑就可以一致了。
mongo是可以的

**Comment by zlazlazl** [comment]
MySQL挺好的呀

**Comment by AprilNEA** [comment]
`v3`版本已完成改需求。
