### ISSUE TITLE
[OS-30] [Feature] 添加卡密充值模式

### ISSUE THREAD

**Issue by JeazW** [AprilNEA/ChatGPT-Admin-Web#4]
你好April大佬，您这个项目期待已久，考不考虑加入：
key余额监控
卡密充值
消息数据库存储

<sub>[OS-30](https://linear.app/renailu/issue/OS-30/[feature]-添加卡密充值模式)</sub>

**Comment by AprilNEA** [comment]
云端同步消息已在计划中，
卡密充值模式会考虑，优先级中等。
