### ISSUE TITLE
现在的项目是否可以直接运行了？

### ISSUE THREAD

**Issue by hedongshu** [AprilNEA/ChatGPT-Admin-Web#43]
我看文档 是不是只差管理的admin界面没实现，用户端和服务端都已经写完了
其他的我是不是可以用postman先调用api来用着

**Comment by AprilNEA** [comment]
你不需要使用 Postman 调用 API，部署完毕后注册即可使用。
如需使用速率限制，需要手动向 Redis 中加入 `plan` 为前缀的 JSON 固定格式字段，目前这一部分可以参考 #43。
