### ISSUE TITLE
"购买"按钮无反应

### ISSUE THREAD

**Issue by luzhenhua1** [AprilNEA/ChatGPT-Admin-Web#45]
作者晚上好，按照部署文档的教程一步一步来的

环境变量中已经填写了XUNHU_PAY_APPID、XUNHU_PAY_APPSECRET、DOMAIN。

但部署出来的前端中点击“购买”依旧无反应

**Comment by AprilNEA** [comment]
1. 确认虎皮椒微信签约。
2. 提供控制台相关截图。

**Comment by luzhenhua1** [comment]
非常感谢您的回复，我确认已经签约开通虎皮椒微信支付。
以下是 Vercel 环境变量部分截图：
![322BDD4A-B5AE-4EC3-8455-4EAA3171C3A5](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/128296338/5fe92cf2-71cd-4b4e-a18c-aa8f2ebd3670)
![F340D633-0D66-4716-98F0-F856F53A0995](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/128296338/08899d1d-d55f-463a-8300-8f71b76b119e)

**Comment by luzhenhua1** [comment]
控制台报错如下：
<img width="1191" alt="77A8103F-630B-462D-95F1-A4F2A86558F0" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/128296338/803f111a-618d-49c9-8bc4-98d6aaea6580">

**Comment by chenzhongd** [comment]
我也遇到了，请问解决了吗

**Comment by Oh-Little-Papaya** [comment]
同遇到 +1

**Comment by zpng** [comment]
+1

**Comment by Yiqian-Liu** [comment]
Same issue.

**Comment by AprilNEA** [comment]
该问题将在新版本中被解决，
