### ISSUE TITLE
[CAW-30] 无法重置限制

### ISSUE THREAD

**Issue by ihjycc** [AprilNEA/ChatGPT-Admin-Web#49]
https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/80345055/a560379e-783f-48d0-a92d-517dcd047291

<sub>[CAW-30](https://linear.app/renailu/issue/CAW-30/无法重置限制)</sub>

**Comment by ihjycc** [comment]
https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/80345055/e1171110-95d3-4088-8f71-4771bf950b55

**Comment by ihjycc** [comment]
重置功能还是存在bug，缓慢点击重置功能后，会出现重置成功，只有快速连续点击会出现重置失败，但是不管显示成功或者失败，都是没有重置成功的。

**Comment by ihjycc** [comment]
https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/80345055/5e78d16a-bee8-4c76-88b7-3277721b5cbe

**Comment by ihjycc** [comment]
问题依然存在，缓慢点了时，会显示重置成功，只有快速点击时，会显示重置失败，但是不管显示什么，都是没有重置成功的

**Comment by AprilNEA** [comment]
重置功能**将**被重做。
