### ISSUE TITLE
INVITATION CODE 邀请代码

### ISSUE THREAD

**Issue by zenchantlive** [AprilNEA/ChatGPT-Admin-Web#50]
I do not know Chinese, Cantonese or Mandarin, so I am using google translate. 

I do not understand how to propagate an invitation code for the user to log in. i do not know where i set these codes up or how to use them. I would like to turn off this feature, only if I can not use it properly. 

我不懂中文、粤语或普通话，所以我使用谷歌翻译。

我不明白如何传播邀请码供用户登录。我不知道我在哪里设置这些代码或如何使用它们。 我想关闭这个功能，除非我不能正常使用它。

![Screenshot 2023-05-12 113640](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/103866469/681c0317-5248-4f97-9538-55aa7db49ae9)

**Comment by AprilNEA** [comment]
As this is optional, you can choose not to fill it out.
Do you want it to disappear from the interface?

**Comment by zenchantlive** [comment]
even when i put nothing it still says i have a wrong password and email or invitation code. I would like to use this but it seems I am unable to log in. can you please help me?

**Comment by AprilNEA** [comment]
We will fix this issue in the new version
