### ISSUE TITLE
[CAW-23] [Feature] 添加 Google Bard 模型

### ISSUE THREAD

**Issue by kugecf** [AprilNEA/ChatGPT-Admin-Web#51]
null

<sub>[CAW-23](https://linear.app/renailu/issue/CAW-23/能添加google-bard的模型吗？)</sub>

**Comment by AprilNEA** [comment]
计划中。

**Comment by AprilNEA** [comment]
Due to the instability of the reverse, `New Bing` has now been canceled, as well as the planned `Google Bard`.
