### ISSUE TITLE
开发者你好，两个问题 邮箱和 界面无法交谈

### ISSUE THREAD

**Issue by onlyhuman028** [AprilNEA/ChatGPT-Admin-Web#56]
1、邮箱 ：ELASTICE 和MAILGUN都 无法收到 注册验证码。但是随便填入6位数字可以进用户界面。

![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/90880928/e6440b40-a71e-4eb4-8bc7-fe69df420f7e)

![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/90880928/28aad75e-5d6f-4122-a36e-5b40b94ae324)

2、用户界面无法聊天

我打openai 新生成了 AIPKEY，在netx web 上使用是正常的。

![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/90880928/0aeb07cc-4ced-4de3-ab50-8f5ce48565f1)

但在admin chatweb 上报错

![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/90880928/3cbcda34-0259-4302-8e0e-ed43566aa9f2)

**Comment by ihjycc** [comment]
感觉是个例，我部署的是正常的

**Comment by tanzhiquan** [comment]
> 感觉是个例，我部署的是正常的

可以分享一下经验吗，我也遇到同样的问题，无法聊天是因为没有配置限制数量

**Comment by onlyhuman028** [comment]
> 感觉是个例，我部署的是正常的

大部分人都碰到了。您是用的哪个容器？vercel还是？
