### ISSUE TITLE
各位大佬，这么好的项目，为啥没有人给顶上去。有后端部署成功的小伙伴吗~分享一下经验

### ISSUE THREAD

**Issue by hieivip** [AprilNEA/ChatGPT-Admin-Web#57]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/54146330/c3a909fb-a0c4-40d4-8f49-f16e6266c710)

**Comment by tanzhiquan** [comment]
后端部署了，但是不知道怎么初始化数据和管理员账号，请大佬解答一下
