### ISSUE TITLE
[CAW-31] 虎皮椒支付无法跳转

### ISSUE THREAD

**Issue by chenzhongd** [AprilNEA/ChatGPT-Admin-Web#58]
使用最新的main分支
开通了第一个微信支付，配置好了XUNHU_PAY_APPID、XUNHU_PAY_APPSECRET还有DOMAIN
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/53546426/cd0a0ae9-4f94-4092-83e5-cadba80f3694)
![1408d1f2b6a82bdb7fc2faaeb47936b](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/53546426/2cd14491-d3a6-499e-aff7-9de00059f667)
![228ddec24cee1323ffbaae4e263f5d8](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/53546426/d65422ad-c681-47be-bf54-16f0f7cd6f1e)
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/53546426/44fabb3a-6d09-4680-bc9e-0ffbbff2b40e)
![4239e4b85deb0a4738a78534775f403](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/53546426/b2634137-0f5b-49e2-82ab-ac525690988d)

<img width="1090" alt="image" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/53546426/055169c2-9f12-4f97-b799-455588ee6586">

<sub>[CAW-31](https://linear.app/renailu/issue/CAW-31/虎皮椒支付无法跳转)</sub>

**Comment by zpng** [comment]
+1

**Comment by Yiqian-Liu** [comment]
Same issue.

**Comment by chan-shen** [comment]
相同问题
