### ISSUE TITLE
登录以及注册页面太过简单，可否考虑在登录注册页面加上 登录后的体验图

### ISSUE THREAD

**Issue by Oh-Little-Papaya** [AprilNEA/ChatGPT-Admin-Web#59]
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/9083709/224284fe-46de-44d6-b418-9e555b67a6b8)
类似这种图

**Comment by MuCqq** [comment]
登陆之前体验两次后弹出提示需要登陆是最好的

**Comment by yyx20202020** [comment]
> 

哪个项目是这种效果？

**Comment by AprilNEA** [comment]
> 登陆之前体验两次后弹出提示需要登陆是最好的

会有被逆向接口的风险，无法很好的限制“仅体验两次”，如果基于 IP 地址限制，误杀范围太广。

目前xin新版的效果是这样，下一步会在页面背景处放上体验图。

![cover2](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/37977109/dcd41711-1e9c-4454-ad70-5da45f60f725)
