### ISSUE TITLE
感谢 AprilNEA将这么好的系统开源，已经成功部署，欢迎大家体验，后期还会不断优化：https://chatgpt.anzyzh.com

### ISSUE THREAD

**Issue by sunnyysky** [AprilNEA/ChatGPT-Admin-Web#63]

**Comment by sunnyysky** [comment]
https://chatgpt.anzyzh.com

**Comment by Oh-Little-Papaya** [comment]
怎么解决 支付的问题呢

**Comment by wuyouw** [comment]
> https://chatgpt.anzyzh.com

想问一下，你后端是怎么搭建的？

**Comment by wuyouw** [comment]
想问一下你后端是怎么搭建的，我登陆提示 /api/login 这个接口是404
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/6253519/fcfaec79-e694-4296-b39f-f516590939d8)

**Comment by etimes2008** [comment]
> 想问一下你后端是怎么搭建的，我登陆提示 /api/login 这个接口是404 ![image](https://user-images.githubusercontent.com/6253519/239743449-fcfaec79-e694-4296-b39f-f516590939d8.png)

我一样,不过是401.根据它的教程搭的.感觉是半成品?
