### ISSUE TITLE
[CAW-25] 由于个人安排，本项目将不会更新直到5月31日

### ISSUE THREAD

**Issue by AprilNEA** [AprilNEA/ChatGPT-Admin-Web#66]
null

<sub>[CAW-25](https://linear.app/renailu/issue/CAW-25/由于个人安排，本项目将不会更新直到5月31日)</sub>

**Comment by AprilNEA** [comment]
目前项目已经在重构中，预计在 6 月 7 日发布正式版。

**Comment by Mingxiangyu** [comment]
> 目前项目已经在重构中，预计在 6 月 7 日发布正式版。

哈哈期待期待
