### ISSUE TITLE
404: NOT_FOUND

### ISSUE THREAD

**Issue by zjjqw** [AprilNEA/ChatGPT-Admin-Web#7]
部署后运行报错
项目地址：https://chat-gpt-admin-642eoyk64-aiprm.vercel.app/
404: NOT_FOUND
Code: NOT_FOUND
ID: sfo1::vmptb-1683186861109-8a0362ef74d3

[Click here to learn more about this error.](https://vercel.link/404)

![image](https://user-images.githubusercontent.com/21295598/236144451-310afe1c-8062-4840-8249-26a6069f1f86.png)

**Comment by AprilNEA** [comment]
现在你可以在 https://docs.lmo.best/docs/quick-deploy 查看部署步骤

same with #3
