### ISSUE TITLE
[CAW-26] 请问支持railway部署吗？

### ISSUE THREAD

**Issue by bemjimm** [AprilNEA/ChatGPT-Admin-Web#76]
null

<sub>[CAW-26](https://linear.app/renailu/issue/CAW-26/请问支持railway部署吗？)</sub>

**Comment by AprilNEA** [comment]
可以，会在新版本中，进行支持

**Comment by AprilNEA** [comment]
https://github.com/AprilNEA/ChatGPT-Admin-Web/releases/tag/v3.0.0-alpha
