### ISSUE TITLE
vercel部署失败

### ISSUE THREAD

**Issue by xfxx2022** [AprilNEA/ChatGPT-Admin-Web#78]
20:33:19.884chat:build: Failed to compile.
20:33:10.884chat:build:
20:33:10.885chat:build:src/app/(chat)/pricing/page.tsxchat:build: Typeerror: Page"src/app/(chat)/pricing/page.tsx"does notmatch the required types of a Next.js Page.20:33:10.885chat:build:"prices”is not avalid Page export field.
20:33:1885
20:33:10.885chat:build:
2:33:11.032
chat:build:ELIFECYCLECommand failed with exit code 1chat:build:ERROR: command finished with error: command(/vercel/path/apps/chat) pnpm run build exited (1)command (/vercel/patha/apps/chat) pnpm run build exited(1)
20:33:11.050
20:33:11.050
20:33:11.051
20:33:11.052
20:33:11.053
20:33:11.053
Tasks:
Cached :
Time:
20:33:11.054Summary:
2 successful，3totalcached，3total
1m5.588s/vercel/path0/.turbo/runs/2QeLVh1EJu3r5pX2hblxDRG7tBj.json
20:33:11.054
20:33:11.054ERROR run failed: command exited (1)
20:33:11.075Error: Command"npx turbo run build"exited with 1
20:33:11.428BUILD_UTILS_SPAWN_1: Command"npx turbo run build"exited with 1

**Comment by BestLemoon** [comment]
same problem

**Comment by libaxuan** [comment]
同等待解决

**Comment by chan-shen** [comment]
1

**Comment by ZhihaoYangUNSW** [comment]
<img width="746" alt="image" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/56749982/42f8eb8f-1cd6-419f-be51-746d3e789bf4">
在配置文件里加一句这个

**Comment by Mingxiangyu** [comment]
> <img alt="image" width="746" src="https://user-images.githubusercontent.com/56749982/243172071-42f8eb8f-1cd6-419f-be51-746d3e789bf4.png"> 在配置文件里加一句这个

pageExtensions:['page.tsx','page.ts','page.jsx','page.js'],
