### ISSUE TITLE
管理后台部署成功之后，登录的账号密码是什么

### ISSUE THREAD

**Issue by ZhihaoYangUNSW** [AprilNEA/ChatGPT-Admin-Web#83]

**Comment by libaxuan** [comment]
自己QQ注册

**Comment by ZhihaoYangUNSW** [comment]
我现在后台都进不去
<img width="585" alt="image" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/56749982/5d880dc5-48ca-4154-8423-ee094f1b4f73">

**Comment by ZhihaoYangUNSW** [comment]
<img width="454" alt="image" src="https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/56749982/704dd84a-af93-4572-b5e8-bdc37c6623be">
登录请求后，后台报这个错

**Comment by Mingxiangyu** [comment]
> <img alt="image" width="454" src="https://user-images.githubusercontent.com/56749982/243173851-704dd84a-af93-4572-b5e8-bdc37c6623be.png"> 登录请求后，后台报这个错

+1

**Comment by AprilNEA** [comment]
前台重构版本将于两日内发布，后台目前还在开发中，预计一周内发布。
