### ISSUE TITLE
404 This page could not be found.

### ISSUE THREAD

**Issue by eminfan** [AprilNEA/ChatGPT-Admin-Web#85]
https://chat-gpt-admin-web-chat-rho-neon.vercel.app/ 咋回事啊，部署6次了，一直是这样404 求助各位
![image](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/16729869/959f973f-6808-4ebe-bbd1-ddadbeb796be)

**Comment by Mingxiangyu** [comment]
遇见了同样的情况

**Comment by randomAndre** [comment]
我也是这样

**Comment by xdengpao** [comment]
同样的问题

**Comment by immochan** [comment]
同样的问题，部署成功，但是页面404

**Comment by 1441853031** [comment]
+1

**Comment by dev-droid** [comment]
+1

**Comment by ZhuKuang** [comment]
+1

**Comment by itcodes** [comment]
这个如何解决的呀？

**Comment by whitespur** [comment]
+1 怎么解决

**Comment by AprilNEA** [comment]
可以参考 #98，本仓库重构版本将于两日内发布 

> @AprilNEA 这个是部署情况不对吗？

是仓库中的代码有问题，非常抱歉。

**Comment by Mingxiangyu** [comment]
> 可以参考 #98，本仓库重构版本将于两日内发布
> 
> > @AprilNEA 这个是部署情况不对吗？
> 
> 是仓库中的代码有问题，非常抱歉。

好的，期待！作者辛苦了
