### ISSUE TITLE
进度太慢了

### ISSUE THREAD

**Issue by vtea** [AprilNEA/ChatGPT-Admin-Web#96]
连yda的更新都不能及时同步，如果不想运行了，请直接表明

**Comment by snekkenull** [comment]
基本礼仪，懂？

**Comment by ws-nd** [comment]
> 连yda的更新都不能及时同步，如果不想运行了，请直接表明

你给作者发工资了？还是你给项目做出任何贡献了？
如果觉得同步不及时那你提pr啊？
如果你是因为fork了yda的repo搞了个60块钱卖密码的操作割不到韭菜，这边你又部署不明白在这破防了，请直接表明？

**Comment by qianghuang84** [comment]
真是吃完了抹嘴骂娘，开发人员没有义务跟上你的需求。

另外希望这个项目开启github sponsors或上传微信支付或支付宝二维码，给开发人员买杯咖啡提提神。支持这个项目！

**Comment by 1441853031** [comment]
需要定制卡密系统可以联系我，授权码可自动到期

**Comment by byYufeng** [comment]
> 

别出来丢人现眼了
光这个嘴要饭还嫌吃的不够饱
大半夜看见这种下头话就生气
