### ISSUE TITLE
使用作者仓库历史版本解决了部署报错和404

### ISSUE THREAD

**Issue by TPC-Light** [AprilNEA/ChatGPT-Admin-Web#98]
大家可以直接fork这个仓库部署https://github.com/TPC-Light/chat-admin-web-test
这个仓库是我下载部署不会报错的源代码重新上传的
但是我部署后收不到邮件，用的elastice的邮件服务
![Image 2023-6-16 at 18 02](https://github.com/AprilNEA/ChatGPT-Admin-Web/assets/62536247/197f400d-fead-4228-9d9c-dbcfb07498f4)

**Comment by Mingxiangyu** [comment]
哈哈哈感谢大佬分享，我部署试一试

**Comment by TPC-Light** [comment]
> 哈哈哈感谢大佬分享，我部署试一试
> 
> 哈哈不用谢，我也是小白，你部署成功没

**Comment by AprilNEA** [comment]
感谢。本仓库将于2日内完成重构。

**Comment by TPC-Light** [comment]
> 感谢。本仓库将于2日内完成重构。

谢谢作者

**Comment by biostome** [comment]
> 感谢。本仓库将于2日内完成重构。

已经过去11小时了

**Comment by xch0911** [comment]
我用你这个版本，邮件是正常的。但是支付是有问题的。我去看了下作者的demo 支付也是有问题的。你目前解决的怎么样了？

**Comment by iam-tpc** [comment]
> 我用你这个版本，邮件是正常的。但是支付是有问题的。我去看了下作者的demo 支付也是有问题的。你目前解决的怎么样了？

我没整支付的
